### PR TITLE
Provide `operator<<` for `Intensity32u` point type

### LINKED ISSUE #2466: No operator << for pcl::Intensity32u
## Your Environment

* PCL Version: master branch

## Context

```.cpp
std::cout << pcl::Intensity32u() << "\n";
```

will result in link error since
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/impl/point_types.hpp#L443
is declared but **NOT** defined.
## Expected Behavior

Not link error.
## Current Behavior

Link error.
## Code to Reproduce

See the code above.
## Possible Solution

Define the operator `<<` for `pcl::Intensity32u`

### PR DESCRIPTION
**Pull request by csukuangfj**
Fix #2466.

### CODE REVIEW

File: common/src/point_types.cpp [hunk 1]
```diff
@@ -70,6 +70,13 @@ namespace pcl
     return (os);
   }
 
+  std::ostream&
+  operator << (std::ostream& os, const Intensity32u& p)
+  {
+    os << "( " << static_cast<int>(p.intensity) << " )";
```
Comment (taketwo) [inline common/src/point_types.cpp]: We don't want this cast. In the case of `Intensity8u` it's needed because otherwise the value will be output as a character.

Comment (csukuangfj) [reply common/src/point_types.cpp]: @taketwo 
thank you for the review.
Then why is it converted from float to int for the code below
https://github.com/PointCloudLibrary/pcl/blob/8e74b8a4bb03586e285f187303f033e9d983b175/common/src/point_types.cpp#L59-L64

Comment (taketwo) [reply common/src/point_types.cpp]: This I can not say, either a copy/paste or the author wanted to omit fractional part. But for the line in question, casting to signed integer does not make sense. If the stored intensity value is a very large number, say `0xFFFFFFFF`, then an overflow will happen and we will get `-1` printed.

Comment (csukuangfj) [reply common/src/point_types.cpp]: @taketwo 
Fixed!
