### PR TITLE
Change normal_distribution from double to float and remove static_cast.

### LINKED ISSUE #2995: Switching from normal_distribution<> to normal_distribution<float> causes CorrespondenceRejectors.CorrespondenceRejectionPoly to fail
The following changes will cause the tests to fail, even it doesn't change anything relevant.

https://github.com/PointCloudLibrary/pcl/blob/88660062d88bcce91d9ea2f1547f7673c7910a26/test/registration/test_correspondence_rejectors.cpp#L101-L107

```
 std::normal_distribution<float> nd(0.0f, 0.005f); 
 for (auto &point : target) 
 { 
   point.x += nd(rng); 
   point.y += nd(rng); 
   point.z += nd(rng); 
 }
```

### PR DESCRIPTION
**Pull request by larshg**
Fixes #2995.

### CODE REVIEW

File: test/registration/test_correspondence_rejectors.cpp [hunk 1]
```diff
@@ -130,8 +130,9 @@ TEST (CorrespondenceRejectors, CorrespondenceRejectionPoly)
    * but not too many
    */
   EXPECT_GE(accepted_frac, ground_truth_frac);
-  EXPECT_LE(accepted_frac, 1.5f*ground_truth_frac);
-  
+  // Factor 1.5 raised to 1.6 see #2995 for details
```
Comment (kunaltyagi) [inline test/registration/test_correspondence_rejectors.cpp:133]: Maybe mention the reason directly (to account for variance in single and double precision across diff implementations) along with referring to the issue
