### PR TITLE
Fix Memory Leaks

### LINKED ISSUE #3612: Fix Memory Leaks
## Your Environment

* PCL Version: HEAD, CI

## Context
Most of the leaks are in application/test code, which will not impact the core library. But they should be removed nonetheless.

Some of the leaks have been fixed, but there are still some left.

## List of files with leaks
```
ml/src/svm.cpp:2354  error memleakOnRealloc: Common realloc mistake: 'label' nulled but not freed upon failure
ml/src/svm.cpp:2355  error memleakOnRealloc: Common realloc mistake: 'count' nulled but not freed upon failure
ml/src/svm.cpp:3122  error memleakOnRealloc: Common realloc mistake: 'line' nulled but not freed upon failure
ml/src/svm.cpp:3523  error memleakOnRealloc: Common realloc mistake: 'label' nulled but not freed upon failure
ml/src/svm.cpp:3524  error memleakOnRealloc: Common realloc mistake: 'count' nulled but not freed upon failure
ml/src/svm.cpp:3181  error memleak: Memory leak: model.scaling
people/apps/main_ground_based_people_detection.cpp:255  error memleak: Memory leak: interface
surface/src/3rdparty/opennurbs/opennurbs_beam.cpp:868  warning nullPointerRedundantCheck: Either the condition '0!=polycurve' is redundant or there is possible null pointer dereference: polycurve.
surface/src/3rdparty/opennurbs/opennurbs_beam.cpp:2517  error nullPointer: Possible null pointer dereference: k
surface/src/3rdparty/opennurbs/opennurbs_beam.cpp:2962  error nullPointer: Possible null pointer dereference: null_brep_pointer
surface/src/3rdparty/opennurbs/opennurbs_beam.cpp:2936  warning nullPointerRedundantCheck: Either the condition 'newbrep' is redundant or there is possible null pointer dereference: newbrep.
surface/src/3rdparty/opennurbs/opennurbs_brep_tools.cpp:1269  warning nullPointerRedundantCheck: Either the condition '!brep' is redundant or there is possible null pointer dereference: brep.
surface/src/3rdparty/opennurbs/opennurbs_brep_tools.cpp:1860  warning nullPointerRedundantCheck: Either the condition '!Srf' is redundant or there is possible null pointer dereference: Srf.
surface/src/3rdparty/opennurbs/opennurbs_polycurve.cpp:2803  warning nullPointerRedundantCheck: Either the condition 'pLeftSide' is redundant or there is possible null pointer dereference: pLeftSide.
surface/src/3rdparty/opennurbs/opennurbs_polycurve.cpp:2808  warning nullPointerRedundantCheck: Either the condition 'pRightSide' is redundant or there is possible null pointer dereference: pRightSide.
surface/src/3rdparty/poisson4/marching_cubes_poisson.cpp:752  error uninitvar: Uninitialized variable: v
surface/src/3rdparty/poisson4/marching_cubes_poisson.cpp:867  error uninitvar: Uninitialized variable: v
surface/src/3rdparty/poisson4/marching_cubes_poisson.cpp:883  error uninitvar: Uninitialized variable: v
test/2d/test_2d.cpp:124  error memleak: Memory leak: k
test/2d/test_2d.cpp:124  error memleak: Memory leak: conv
test/2d/test_2d.cpp:157  error memleak: Memory leak: k
test/2d/test_2d.cpp:157  error memleak: Memory leak: conv
test/2d/test_2d.cpp:296  error memleak: Memory leak: morph
test/2d/test_2d.cpp:329  error memleak: Memory leak: morph
test/2d/test_2d.cpp:362  error memleak: Memory leak: morph
test/2d/test_2d.cpp:395  error memleak: Memory leak: morph
test/io/test_octree_compression.cpp:111  error memleak: Memory leak: pointcloud_encoder
test/io/test_octree_compression.cpp:111  error memleak: Memory leak: pointcloud_decoder
test/io/test_octree_compression.cpp:156  error memleak: Memory leak: pointcloud_encoder
test/io/test_octree_compression.cpp:156  error memleak: Memory leak: pointcloud_decoder
test/search/test_auto_search.cpp:187  error memleak: Memory leak: octree
test/search/test_auto_search.cpp:311  error memleak: Memory leak: kdtree
test/search/test_auto_search.cpp:309  error memleak: Memory leak: kdtree
test/search/test_auto_search.cpp:325  error memleak: Memory leak: search
test/search/test_auto_search.cpp:344  error memleak: Memory leak: kdtree
test/search/test_flann_search.cpp:128  error memleak: Memory leak: FlannSearch
test/search/test_flann_search.cpp:127  error memleak: Memory leak: FlannSearch
test/search/test_flann_search.cpp:174  error memleak: Memory leak: FlannSearch
test/search/test_flann_search.cpp:207  error memleak: Memory leak: FlannSearch
test/search/test_flann_search.cpp:252  error memleak: Memory leak: flann_search
test/search/test_flann_search.cpp:378  error memleak: Memory leak: FlannSearch
test/search/test_kdtree.cpp:123  error memleak: Memory leak: kdtree
test/search/test_kdtree.cpp:122  error memleak: Memory leak: kdtree
test/search/test_kdtree.cpp:166  error memleak: Memory leak: kdtree
test/search/test_kdtree.cpp:196  error memleak: Memory leak: kdtree
test/search/test_kdtree.cpp:208  error memleak: Memory leak: kdtree
test/search/test_octree.cpp:167  error memleak: Memory leak: octree
test/search/test_organized_index.cpp:173  error memleak: Memory leak: organizedNeighborSearch
test/search/test_organized_index.cpp:202  error memleak: Memory leak: organizedNeighborSearch
test/search/test_organized_index.cpp:375  error memleak: Memory leak: organizedNeighborSearch
test/search/test_organized_index.cpp:461  error memleak: Memory leak: organizedNeighborSearch
test/search/test_organized_index.cpp:600  error memleak: Memory leak: organizedNeighborSearch
test/test_recognition_ransac_based_ORROctree.cpp:117  error memleak: Memory leak: new_model
tools/mesh_sampling.cpp:92  error nullPointer: Possible null pointer dereference: ptIds
tools/mesh_sampling.cpp:93  error nullPointer: Possible null pointer dereference: ptIds
tools/mesh_sampling.cpp:94  error nullPointer: Possible null pointer dereference: ptIds
tools/mesh_sampling.cpp:115  error nullPointer: Possible null pointer dereference: ptIds
tools/mesh_sampling.cpp:116  error nullPointer: Possible null pointer dereference: ptIds
tools/mesh_sampling.cpp:117  error nullPointer: Possible null pointer dereference: ptIds
tools/oni_viewer_simple.cpp:210  error memleak: Memory leak: grabber
visualization/src/point_cloud_handlers.cpp:741  error memleak: Memory leak: pts
```
The format allows most editors to open the file using `Ctrl+click` (no, not vim :stuck_out_tongue: )

### PR DESCRIPTION
**Pull request by shiveshkhaitan**
Resolves #3612. I have used cppcheck to detect memory leaks.

### CODE REVIEW

File: gpu/people/tools/people_tracking.cpp [hunk 1]
```diff
@@ -125,5 +125,6 @@ int main(int argc, char** argv)
   }
   /// Run the app
   app.run();
+  delete(app.m_proc);
```
Comment (SergioRAgostinho) [inline gpu/people/tools/people_tracking.cpp]: This is not the way to go.  `app.m_proc` is part of `PeopleTrackingApp` an is should be released if needed by its destructor.

Furthermore, the tree loading code from lines 114-125 should be encapsulated in a single method.

File: ml/src/svm.cpp [hunk 2]
```diff
@@ -2351,8 +2351,14 @@ svm_group_classes(const svm_problem* prob,
...
-        label = static_cast<int*>(realloc(label, max_nr_class * sizeof(int)));
-        count = static_cast<int*>(realloc(count, max_nr_class * sizeof(int)));
+        int* label_temp = static_cast<int*>(realloc(label, max_nr_class * sizeof(int)));
+        if (label_temp) {
+          label = label_temp;
+        }
+        int* count_temp = static_cast<int*>(realloc(count, max_nr_class * sizeof(int)));
+        if (count_temp) {
+          count = count_temp;
+        }
```
Comment (SergioRAgostinho) [inline ml/src/svm.cpp]: Move the changes in this file to a separate PR. It needs more fundamental changes. It should be using vectors instead of handling reallocs manually.

File: test/2d/test_2d.cpp [hunk 3]
```diff
@@ -121,6 +121,9 @@ TEST (Convolution, borderOptions)
     EXPECT_NEAR ((*output_cloud)(0,i).intensity, ((*input_cloud)(1,i).intensity), 1);
     EXPECT_NEAR ((*output_cloud)(width-1,i).intensity, (-(*input_cloud)(width-2,i).intensity), 1);
   }
+
+  delete(k);
+  delete(conv);
```
Comment (SergioRAgostinho) [inline test/2d/test_2d.cpp]: The variables `k` and `conv` don't need to be pointer in the first place.

File: test/2d/test_2d.cpp [hunk 4]
```diff
@@ -154,6 +157,8 @@ TEST (Convolution, gaussianSmooth)
     for (int j = 1; j < width - 1; j++)
       EXPECT_NEAR ((*output_cloud)(j,i).intensity, (*gt_output_cloud)(j,i).intensity, 1);
 
+  delete(k);
+  delete(conv);
```
Comment (SergioRAgostinho) [inline test/2d/test_2d.cpp]: The variables `k` and `conv` don't need to be pointer in the first place.

File: test/2d/test_2d.cpp [hunk 5]
```diff
@@ -293,6 +298,7 @@ TEST(Morphology, erosion)
     for (int j = 1; j < width - 1; j++)
       EXPECT_NEAR ((*output_cloud)(j,i).intensity, (*gt_output_cloud)(j,i).intensity/255.0, 1);
 
+  delete(morph);
```
Comment (SergioRAgostinho) [inline test/2d/test_2d.cpp]: `morph` doesn't need to be a pointer.

File: visualization/src/point_cloud_handlers.cpp [hunk 6]
```diff
@@ -738,6 +738,8 @@ pcl::visualization::PointCloudGeometryHandler<pcl::PCLPointCloud2>::getGeometry
     data->SetArray (&pts[0], j * 3, 0);
     points->SetData (data);
   }
+
+  free(pts);
```
Comment (SergioRAgostinho) [inline visualization/src/point_cloud_handlers.cpp]: `pts` needs to be a `std::vector`  instead.

File: test/2d/test_2d.cpp (hunk 3 above)
Comment (shiveshkhaitan) [reply test/2d/test_2d.cpp]: Should I make these and the other pointers normal variables?

Comment (SergioRAgostinho) [reply test/2d/test_2d.cpp]: Exactly. :+1:

File: gpu/people/tools/people_tracking.cpp (hunk 1 above)
Comment (shiveshkhaitan) [reply gpu/people/tools/people_tracking.cpp]: I have made the changes in 6c1e94b

File: ml/src/svm.cpp (hunk 2 above)
Comment (shiveshkhaitan) [reply ml/src/svm.cpp]: I have reverted the changes for these now except freeing `model->scaling`

File: test/io/test_octree_compression.cpp [hunk 7]
```diff
@@ -63,8 +63,8 @@ TEST (PCL, OctreeDeCompressionRandomPointXYZRGBA)
   for (int compression_profile = pcl::io::LOW_RES_ONLINE_COMPRESSION_WITHOUT_COLOR;
     compression_profile != pcl::io::COMPRESSION_PROFILE_COUNT; ++compression_profile) {
     // instantiate point cloud compression encoder/decoder
-    pcl::io::OctreePointCloudCompression<pcl::PointXYZRGBA>* pointcloud_encoder = new pcl::io::OctreePointCloudCompression<pcl::PointXYZRGBA>((pcl::io::compression_Profiles_e) compression_profile, false);
-    pcl::io::OctreePointCloudCompression<pcl::PointXYZRGBA>* pointcloud_decoder = new pcl::io::OctreePointCloudCompression<pcl::PointXYZRGBA>();
+    pcl::io::OctreePointCloudCompression<pcl::PointXYZRGBA> pointcloud_encoder((pcl::io::compression_Profiles_e) compression_profile, false);
+    pcl::io::OctreePointCloudCompression<pcl::PointXYZRGBA> pointcloud_decoder();
```
Comment (kunaltyagi) [inline test/io/test_octree_compression.cpp]: Remove the brackets here. This isn't a variable but a function declaration

File: test/search/test_auto_search.cpp [hunk 8]
```diff
@@ -303,35 +301,31 @@ TEST (PCL, KdTreeWrapper_nearestKSearch)
...
-
-  delete(kdtree);
 }	
 
 
 /* Function to auto evaluate the best search structure for the given dataset */
 TEST (PCL, AutoTunedSearch_Evaluate)
 {
-  pcl::search::Search<PointXYZ>* search = new pcl::search::AutotunedSearch<PointXYZ>(pcl::search::AUTO_TUNED);
+  pcl::search::Search<PointXYZ> search (pcl::search::AUTO_TUNED);
```
Comment (kunaltyagi) [inline test/search/test_auto_search.cpp]: Type of search is wrong. Should be `AutoTunedSearch`

File: test/search/test_flann_search.cpp [hunk 9]
```diff
@@ -257,7 +250,7 @@ TEST (PCL, FlannSearch_knnByIndex)
 
   }
 
-  delete(flann_search);
+  delete (flann_search);
```
Comment (kunaltyagi) [inline test/search/test_flann_search.cpp]: You forgot to convert this variable from a pointer type.

File: visualization/src/point_cloud_handlers.cpp [hunk 10]
```diff
@@ -689,9 +689,9 @@ pcl::visualization::PointCloudGeometryHandler<pcl::PCLPointCloud2>::getGeometry
   vtkIdType nr_points = cloud_->width * cloud_->height;
 
   // Add all points
-  float dim;
+  float dim_x, dim_y, dim_z;
   vtkIdType j = 0;    // true point index
-  float* pts = static_cast<float*> (malloc (nr_points * 3 * sizeof (float)));
+  std::vector<float> pts;
```
Comment (kunaltyagi) [inline visualization/src/point_cloud_handlers.cpp]: The size is known. You can reserve it.

File: gpu/people/tools/people_tracking.cpp [hunk 11]
```diff
@@ -32,6 +32,13 @@ class PeopleTrackingApp
   public:
     PeopleTrackingApp () : viewer ("PCL People Tracking App") {}
 
+    ~PeopleTrackingApp ()
+    {
+      if (m_proc) {
```
Comment (kunaltyagi) [inline gpu/people/tools/people_tracking.cpp]: Use `unique_ptr` for m_proc instead. You're using `new` to create m_proc but `free` to delete. That's a big issue. It's tools so this shouldn't be a breaking change to modify the interface to accept a unique_ptr in ctor.

File: ml/src/svm.cpp [hunk 12]
```diff
@@ -2351,14 +2351,8 @@ svm_group_classes(const svm_problem* prob,
...
         max_nr_class *= 2;
-        int* label_temp = static_cast<int*>(realloc(label, max_nr_class * sizeof(int)));
-        if (label_temp) {
-          label = label_temp;
-        }
-        int* count_temp = static_cast<int*>(realloc(count, max_nr_class * sizeof(int)));
-        if (count_temp) {
-          count = count_temp;
-        }
+        label = static_cast<int*>(realloc(label, max_nr_class * sizeof(int)));
```
Comment (kunaltyagi) [inline ml/src/svm.cpp]: Remove changes for this file. These changes don't affect memory leaks anyways and changes behavior in case of bad_alloc

Comment (shiveshkhaitan) [reply ml/src/svm.cpp]: Actually this is the reverted code.  The current changes are for model->scaling only.  Should I revert them as well?

File: tools/oni_viewer_simple.cpp [hunk 13]
```diff
@@ -206,5 +206,6 @@ main(int argc, char ** argv)
     v.run();
   }
 
+  delete(grabber);
```
Comment (kunaltyagi) [inline tools/oni_viewer_simple.cpp]: Use `unique_ptr` instead if pointer is needed. But it's not. Even here I don't see the need of a pointer.

File: ml/src/svm.cpp (hunk 12 above)
Comment (kunaltyagi) [reply ml/src/svm.cpp]: No, keep the model->scaling changes. I saw these changes before you reverted them

File: tools/oni_viewer_simple.cpp (hunk 13 above)
Comment (shiveshkhaitan) [reply tools/oni_viewer_simple.cpp]: https://github.com/PointCloudLibrary/pcl/blob/6c1e94b6d06d66d0c08de4a18f82ff24a97332aa/tools/oni_viewer_simple.cpp#L195 
This wasn't working without a pointer. I will look into it again

Comment (kunaltyagi) [reply tools/oni_viewer_simple.cpp]: That's capture by value, hence needs a pointer. But you can capture by reference IFF you can guarantee that trigger will not outlast grabber.

File: test/search/test_flann_search.cpp (hunk 9 above)
Comment (shiveshkhaitan) [reply test/search/test_flann_search.cpp]: https://github.com/PointCloudLibrary/pcl/blob/6c1e94b6d06d66d0c08de4a18f82ff24a97332aa/test/search/test_flann_search.cpp#L243 This `nearestKSearch` is not implemented in `FlannSearch`. So I could not change it.

Comment (SergioRAgostinho) [reply test/search/test_flann_search.cpp]: Assuming you really changed the pointer to a normal variable, if it was really not implemented, then `flann_search->nearestKSearch` would also have yielded a compiler error. The problem is likely something else.

Comment (shiveshkhaitan) [reply test/search/test_flann_search.cpp]: https://github.com/PointCloudLibrary/pcl/blob/6c1e94b6d06d66d0c08de4a18f82ff24a97332aa/test/search/test_flann_search.cpp#L216
This cast to `pcl::search::Search<PointXYZ>` probably does something as the function is implemented in the parent class

Comment (SergioRAgostinho) [reply test/search/test_flann_search.cpp]: The child class inherits all the public methods from base, so having the cast to base should not matter as long as the methods are virtual, which they appear to be. Can you post here the diff with the changes you tried and the compilation error log?

Comment (shiveshkhaitan) [reply test/search/test_flann_search.cpp]: Diff
```
-  pcl::search::Search<PointXYZ>* flann_search = new pcl::search::FlannSearch<PointXYZ> (new search::FlannSearch<PointXYZ>::KdTreeIndexCreator);
+  pcl::search::FlannSearch<PointXYZ> flann_search (new search::FlannSearch<PointXYZ>::KdTreeIndexCreator)
```

Error: 

```
pcl/test/search/test_flann_search.cpp:243:101: error: no matching function for call to ‘pcl::search::FlannSearch<pcl::PointXYZ>::nearestKSearch(pcl::PointCloud<pcl::PointXYZ>&, __gnu_cxx::__alloc_traits<std::allocator<int> >::value_type&, unsigned int&, std::vector<int>&, std::vector<float>&)’
     flann_search.nearestKSearch (cloud_big,query_indices[i], no_of_neighbors, k_indices, k_distances);

```

Comment (SergioRAgostinho) [reply test/search/test_flann_search.cpp]: It was a little more involved than I expected
```diff
diff --git a/search/include/pcl/search/flann_search.h b/search/include/pcl/search/flann_search.h
index 95f61056d..6dd7e63a7 100644
--- a/search/include/pcl/search/flann_search.h
+++ b/search/include/pcl/search/flann_search.h
@@ -260,6 +260,8 @@ namespace pcl
         void
         setInputCloud (const PointCloudConstPtr& cloud, const IndicesConstPtr& indices = IndicesConstPtr ()) override;
 
+        using Search<PointT>::nearestKSearch;
+
         /** \brief Search for the k-nearest neighbors for the given query point.
           * \param[in] point the given query point
           * \param[in] k the number of neighbors to search for
diff --git a/test/search/test_flann_search.cpp b/test/search/test_flann_search.cpp
index b3f28ddee..b1ff6d3bd 100644
--- a/test/search/test_flann_search.cpp
+++ b/test/search/test_flann_search.cpp
@@ -213,9 +213,12 @@ TEST (PCL, FlannSearch_knnByIndex)
   unsigned int no_of_neighbors = 3;
 
 
-  pcl::search::Search<PointXYZ>* flann_search = new pcl::search::FlannSearch<PointXYZ> (new search::FlannSearch<PointXYZ>::KdTreeIndexCreator);
+  pcl::search::FlannSearch<PointXYZ> flann_search (
+    true,
+    search::FlannSearch<PointXYZ>::FlannIndexCreatorPtr (new search::FlannSearch<PointXYZ>::KdTreeIndexCreator)
+  );
   //FlannSearch->initSearchDS ();
-  flann_search->setInputCloud (cloud_big.makeShared ());
+  flann_search.setInputCloud (cloud_big.makeShared ());
 
   std::vector< std::vector< float > > dists;
   std::vector< std::vector< int > > indices;
@@ -224,7 +227,7 @@ TEST (PCL, FlannSearch_knnByIndex)
   {
     query_indices.push_back (int (i));
   }
-  flann_search->nearestKSearch (cloud_big, query_indices,no_of_neighbors,indices,dists);
+  flann_search.nearestKSearch (cloud_big, query_indices,no_of_neighbors,indices,dists);
 
   std::vector<int> k_indices;
   k_indices.resize (no_of_neighbors);
@@ -233,14 +236,14 @@ TEST (PCL, FlannSearch_knnByIndex)
 
   for (std::size_t i = 0; i < query_indices.size (); ++i)
   {
-    flann_search->nearestKSearch (cloud_big[2*i], no_of_neighbors, k_indices, k_distances);
+    flann_search.nearestKSearch (cloud_big[2*i], no_of_neighbors, k_indices, k_distances);
     EXPECT_EQ (k_indices.size (), indices[i].size ());
     EXPECT_EQ (k_distances.size (), dists[i].size ());
     for (std::size_t j = 0; j< no_of_neighbors; j++)
     {
       EXPECT_TRUE (k_indices[j] == indices[i][j] || k_distances[j] == dists[i][j]);
     }
-    flann_search->nearestKSearch (cloud_big,query_indices[i], no_of_neighbors, k_indices, k_distances);
+    flann_search.nearestKSearch (cloud_big, query_indices[i], no_of_neighbors, k_indices, k_distances);
     EXPECT_EQ (k_indices.size (), indices[i].size ());
     EXPECT_EQ (k_distances.size (), dists[i].size ());
     for (std::size_t j = 0; j< no_of_neighbors; j++)
```

Intuitions into what happened:
https://stackoverflow.com/questions/1896830/why-should-i-use-the-using-keyword-to-access-my-base-class-method
https://isocpp.org/wiki/faq/strange-inheritance#hiding-rule

Comment (kunaltyagi) [reply test/search/test_flann_search.cpp]: > Are we likely gonna change this default?

That doesn't matter, right? We're not testing the mechanism here, so the new version is actually better IMO since it tests the actual class as presented to the user.

File: test/io/test_octree_compression.cpp [hunk 14]
```diff
@@ -120,8 +120,8 @@ TEST (PCL, OctreeDeCompressionRandomPointXYZ)
         compression_profile != pcl::io::COMPRESSION_PROFILE_COUNT; ++compression_profile)
   {
     // instantiate point cloud compression encoder/decoder
-    pcl::io::OctreePointCloudCompression<pcl::PointXYZ>* pointcloud_encoder = new pcl::io::OctreePointCloudCompression<pcl::PointXYZ>((pcl::io::compression_Profiles_e) compression_profile, false);
-    pcl::io::OctreePointCloudCompression<pcl::PointXYZ>* pointcloud_decoder = new pcl::io::OctreePointCloudCompression<pcl::PointXYZ>();
+    pcl::io::OctreePointCloudCompression<pcl::PointXYZ> pointcloud_encoder((pcl::io::compression_Profiles_e) compression_profile, false);
+    pcl::io::OctreePointCloudCompression<pcl::PointXYZ> pointcloud_decoder();
```
Comment (kunaltyagi) [inline test/io/test_octree_compression.cpp]:
```suggestion
    pcl::io::OctreePointCloudCompression<pcl::PointXYZ> pointcloud_decoder;
```

File: gpu/people/tools/people_tracking.cpp [hunk 15]
```diff
@@ -91,6 +91,22 @@ int print_help()
...
+  app.m_proc = std::make_shared<pcl::people::trees::MultiTreeLiveProc>(fin0);
+  fin0.close();
+
+  /// Load the other tree files
+  for(int ti=1;ti<numTrees;++ti) {
+    std::ifstream fin(treeFilenames[ti].c_str() );
+    assert(fin.is_open() );
+    app.m_proc->addTree(fin);
+    fin.close();
+  }
```
Comment (SergioRAgostinho) [inline gpu/people/tools/people_tracking.cpp]:
```suggestion
  for (const auto& file : treeFilenames)
  {
    std::ifstream fin (file);
    assert (fin.is_open ());
    app.m_proc->addTree(fin);
  }
```

**Comment by kunaltyagi** [comment]
Please use `memory.h` instead of `make_shared.h` which has been recently deprecated

File: gpu/people/tools/people_tracking.cpp [hunk 16]
```diff
@@ -72,12 +73,27 @@ class PeopleTrackingApp
...
+      for (const auto& file : treeFilenames)
+      {
+        std::ifstream fin (file);
+        assert (fin.is_open());
+        m_proc->addTree(fin);
+      }
+    }
+
+    pcl::visualization::CloudViewer                           viewer;
+    boost::shared_ptr<pcl::people::trees::MultiTreeLiveProc>  m_proc;
```
Comment (SergioRAgostinho) [inline gpu/people/tools/people_tracking.cpp]:
```suggestion
    std::unique_ptr<pcl::people::trees::MultiTreeLiveProc>  m_proc;
```

There's no reason to use a shared pointer here. The class is not being passed around. This is a tool and not part of the library interface so we can use std pointers directly.

File: gpu/people/tools/people_tracking.cpp [hunk 17]
```diff
@@ -72,12 +73,27 @@ class PeopleTrackingApp
...
-    pcl::people::trees::MultiTreeLiveProc*  m_proc;
-    cv::Mat                                 m_lmap;
-    cv::Mat                                 m_cmap;
-    cv::Mat                                 cmap;
-    cv::Mat                                 m_bmap;
+    void load_tree(std::string treeFilenames[4], int numTrees)
+    {
+      std::ifstream fin0 (treeFilenames[0]);
+      assert(fin0.is_open());
+      m_proc = pcl::make_shared<pcl::people::trees::MultiTreeLiveProc>(fin0);
```
Comment (SergioRAgostinho) [inline gpu/people/tools/people_tracking.cpp]:
```suggestion
      m_proc = std::make_unique<pcl::people::trees::MultiTreeLiveProc> (fin0);
```

MultiTreeLiveProc is a GPU class without eigen objects inside and pcl does not provide a `make_unique` method. Even if it did, it would spew a boost pointer which we do not need for this particular case.

File: gpu/people/tools/people_tracking.cpp [hunk 18]
```diff
@@ -19,6 +19,7 @@
 #include <pcl/io/openni_grabber.h>
 #include <pcl/visualization/cloud_viewer.h>
 #include <pcl/console/parse.h>
+#include <pcl/memory.h>
```
Comment (SergioRAgostinho) [inline gpu/people/tools/people_tracking.cpp]: You can remove this now.

File: gpu/people/tools/people_tracking.cpp (hunk 16 above)
Comment (SergioRAgostinho) [reply gpu/people/tools/people_tracking.cpp]: I realized I've just contradicted my previous review. I'm terribly sorry. I came with a fresh pair of eyes without looking at the prior comments and noticed some inconsistencies. Again sorry for the extra noise.

Comment (shiveshkhaitan) [reply gpu/people/tools/people_tracking.cpp]: No problem at all. Just to clarify, I should convert `m_proc` to `std::unique_ptr`, right?

Comment (SergioRAgostinho) [reply gpu/people/tools/people_tracking.cpp]: Exactly.
