### PR TITLE
Fix the covariance calculation as suggested by @zxd123

### LINKED ISSUE #4463: [Filters] Wrong computation in VoxelGridCovariance
Hi! There is a bug in the pcl/filters/include/pcl/filters/impl/voxel_grid_covariance.hpp line 327
The code is `leaf.cov_ *= (leaf.nr_points - 1.0) / leaf.nr_points;`.But according to the formula it should be
`leaf.cov_ *=  leaf.nr_points / (leaf.nr_points - 1.0);`
But it doesn't seem to matter much.

### PR DESCRIPTION
**Pull request by kunaltyagi**
Fixes #4463

### CODE REVIEW

File: filters/include/pcl/filters/impl/voxel_grid_covariance.hpp [hunk 1]
```diff
@@ -323,8 +323,9 @@ pcl::VoxelGridCovariance<PointT>::applyFilter (PointCloud &output)
         voxel_centroids_leaf_indices_.push_back (static_cast<int> (it->first));
 
       // Single pass covariance calculation
-      leaf.cov_ = (leaf.cov_ - 2 * (pt_sum * leaf.mean_.transpose ())) / leaf.nr_points + leaf.mean_ * leaf.mean_.transpose ();
-      leaf.cov_ *= (leaf.nr_points - 1.0) / leaf.nr_points;
+      const auto additional_num = leaf.nr_points + leaf.mean_ * lead.mean_.transpose() -
```
Comment (kunaltyagi) [inline filters/include/pcl/filters/impl/voxel_grid_covariance.hpp:326]:
```suggestion
      const auto additional_num = leaf.nr_points * leaf.mean_ * lead.mean_.transpose() -
```

File: filters/include/pcl/filters/impl/voxel_grid_covariance.hpp [hunk 2]
```diff
@@ -323,8 +323,9 @@ pcl::VoxelGridCovariance<PointT>::applyFilter (PointCloud &output)
         voxel_centroids_leaf_indices_.push_back (static_cast<int> (it->first));
 
       // Single pass covariance calculation
-      leaf.cov_ = (leaf.cov_ - 2 * (pt_sum * leaf.mean_.transpose ())) / leaf.nr_points + leaf.mean_ * leaf.mean_.transpose ();
-      leaf.cov_ *= (leaf.nr_points - 1.0) / leaf.nr_points;
+      const auto additional_num = leaf.nr_points * leaf.mean_ * lead.mean_.transpose() -
```
Comment (mvieth) [inline filters/include/pcl/filters/impl/voxel_grid_covariance.hpp:326]:
```suggestion
      const auto additional_num = leaf.nr_points * leaf.mean_ * leaf.mean_.transpose() -
```

Comment (mvieth) [inline filters/include/pcl/filters/impl/voxel_grid_covariance.hpp:326]: Are you sure that using `auto` here is ok? http://eigen.tuxfamily.org/dox/TopicPitfalls.html

Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/voxel_grid_covariance.hpp]: Sure. I'll not use auto. BTW, should I rearrange the equation to use 1 transpose or leave it as it is?

Comment (mvieth) [reply filters/include/pcl/filters/impl/voxel_grid_covariance.hpp]: Hm, since `pt_sum = leaf.nr_points * leaf.mean_` , `additional_num` is basically just `- pt_sum * leaf.mean_.transpose()`

File: filters/include/pcl/filters/impl/voxel_grid_covariance.hpp [hunk 3]
```diff
@@ -323,8 +323,7 @@ pcl::VoxelGridCovariance<PointT>::applyFilter (PointCloud &output)
         voxel_centroids_leaf_indices_.push_back (static_cast<int> (it->first));
 
       // Single pass covariance calculation
-      leaf.cov_ = (leaf.cov_ - 2 * (pt_sum * leaf.mean_.transpose ())) / leaf.nr_points + leaf.mean_ * leaf.mean_.transpose ();
-      leaf.cov_ *= (leaf.nr_points - 1.0) / leaf.nr_points;
+      leaf.cov_ = (leaf.cov_ - pt_sum * leaf.mean_.transpose()) / (leaf.nr_points - 1.0);
```
Comment (zxd123) [inline filters/include/pcl/filters/impl/voxel_grid_covariance.hpp:326]: Hm... I'm sorry ,but I think the code here should be `leaf.cov_ = (leaf.cov_ - 2 * (pt_sum * leaf.mean_.transpose ()) + leaf.nr_points * leaf.mean_ * leaf.mean_.transpose ())  / (leaf.nr_points - 1.0);` rather than `leaf.cov_ = (leaf.cov_ - pt_sum * leaf.mean_.transpose()) / (leaf.nr_points - 1.0);`

**Review by zxd123 — CHANGES_REQUESTED** [review]
Hm... I'm sorry ,but I think the code here should be leaf.cov_ = (leaf.cov_ - 2 * (pt_sum * leaf.mean_.transpose ()) + leaf.nr_points * leaf.mean_ * leaf.mean_.transpose ()) / (leaf.nr_points - 1.0); rather than leaf.cov_ = (leaf.cov_ - pt_sum * leaf.mean_.transpose()) / (leaf.nr_points - 1.0);

File: filters/include/pcl/filters/impl/voxel_grid_covariance.hpp (hunk 2 above)
Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/voxel_grid_covariance.hpp]: PTAL

Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/voxel_grid_covariance.hpp]: @mvieth

File: filters/include/pcl/filters/impl/voxel_grid_covariance.hpp (hunk 3 above)
Comment (mvieth) [reply filters/include/pcl/filters/impl/voxel_grid_covariance.hpp:326]: Here is a short derivation of the formula:
```
1/(m-1) sum((y-mean)(y-mean)^T)
1/(m-1) sum(y*y^T - mean*y^T - y*mean^T + mean*mean^T)
1/(m-1) (sum(y*y^T) - sum(mean*y^T) - sum(y*mean^T) + sum(mean*mean^T))
1/(m-1) (sum(y*y^T) - mean*sum(y^T) - sum(y)*mean^T + m*mean*mean^T)
1/(m-1) (sum(y*y^T) - m*mean*mean^T - m*mean*mean^T + m*mean*mean^T) because sum(y)=m*mean
1/(m-1) (sum(y*y^T) - m*mean*mean^T)
1/(m-1) (sum(y*y^T) - sum(y)*mean^T)
```

**Review by mvieth — APPROVED** [review]

**Review by koide3 — APPROVED** [review]
LGTM
