### PR TITLE
Use size_t instead of a signed 32 bit integer to compute addres…

### LINKED ISSUE #3417: pcl::CropBox<pcl::PCLPointCloud2> crashes for large point clouds
Due to an integer overflow (the code is using a signed 32 bit integer), applying a crop box filter on a `PCLPointCloud2` crashes when there are more than ca. 45 M points (`point_step` was 48 bytes in my case, i.e. (2^31-1) / 48 ≈ 44,739,242).

## Your Environment
* Operating System and version: Ubuntu 18.04
* Compiler: GCC
* PCL Version: 1.8.1

## Context
`pcl::CropBox<pcl::PCLPointCloud2>` crashes when applying the filter when the point cloud has more than 44,739,242 points.

## Expected Behavior
No crash.

## Current Behavior
Crashing because of an integer overflow in the offset calculation.

## Code to Reproduce
Cropping a point cloud in `PCLPointCloud2` format that has more than ca. 45 M points (parameters don't matter).

## Possible Solution
See pull request.

### PR DESCRIPTION
**Pull request by rhuitl**
Fixes a crash due to an integer overflow when point clouds have more than ca. 44 M points.

Fixes #3417

### CODE REVIEW

File: filters/src/crop_box.cpp [hunk 1]
```diff
@@ -78,8 +78,8 @@ pcl::CropBox<pcl::PCLPointCloud2>::applyFilter (PCLPointCloud2 &output)
   for (size_t index = 0; index < indices_->size (); ++index)
   {
     // Get local point
-    int point_offset = ((*indices_)[index] * input_->point_step);
-    int offset = point_offset + input_->fields[x_idx_].offset;
+    size_t point_offset = static_cast<size_t>((*indices_)[index]) * input_->point_step;
```
Comment (kunaltyagi) [inline filters/src/crop_box.cpp]: Please use `std::size_t` instead.

Also, why is the index being cast to `size_t`? Is that really required? Could you please test if this works without the explicit cast

Comment (rhuitl) [reply filters/src/crop_box.cpp]: Thanks for your prompt reply :) What do you mean by "all occurrences"? I think I found all in `pcl::CropBox`, or did you spot another one?

Good point about the namespace, I'll add `std::`.

Regarding the type cast: `indices_` is declared as `std::vector<int>` in https://github.com/PointCloudLibrary/pcl/blob/6129a3ff78b4d12cff120142d3a18f98236f3bf4/common/include/pcl/pcl_base.h#L60
`point_step` is declared as `uint32_t` in https://github.com/PointCloudLibrary/pcl/blob/6129a3ff78b4d12cff120142d3a18f98236f3bf4/common/include/pcl/PCLPointCloud2.h#L42

This means the multiplication is carried out in 32 bit precision. By casting one of the operators to a wider type, I force the compiler to promote all operands to `size_t` and perform the calculation in 64 bit. See "Evaluating arithmetic expressions" on https://www.learncpp.com/cpp-tutorial/44-implicit-type-conversion-coercion/.

I made this example on https://onlinegdb.com/H1H0HhQYr:
```c++
#include <iostream>

using namespace std;

int main()
{
    int i = 2000000000;
    unsigned int u = 10;
    
    size_t s = i * u;
    size_t s2 = static_cast<size_t>(i) * u;
    
    cout << i << " * " << u << " = " << s << endl;
    cout << i << " * " << u << " = " << s2 << endl;
}
```
Prints:
```
2000000000 * 10 = 2820130816                                                                                                                                                                    
2000000000 * 10 = 20000000000  
```

Comment (kunaltyagi) [reply filters/src/crop_box.cpp]: All occurrences of `size_t` in the lines that you touched. Thanks for the test example. I was under the belief that multiplication is done at full register and then the result is cropped later.
