### PR TITLE
[sample_consensus] Fix inconsistent sample validation

### LINKED ISSUE #5268: [sample_consensus] Inconsistent sample validation in SampleConsensusModelLine, SampleConsensusModelStick, and SampleConsensusModelCylinder
**Describe the bug**

The sample validation in [`isSampleGood(...)`](https://github.com/PointCloudLibrary/pcl/blob/master/sample_consensus/include/pcl/sample_consensus/impl/sac_model_line.hpp#L51) of `SampleConsensusModelLine` has some strong similarity to the validation block in `computeModelCoefficients(...)` ([lines 84 - 86](https://github.com/PointCloudLibrary/pcl/blob/master/sample_consensus/include/pcl/sample_consensus/impl/sac_model_line.hpp#L84-L86)). The piece of code in `computeModelCoefficients(...)` was likely introduced as a workaround to a bug that was fixed in #2488 and also contradicts to the changes introduced in 36c2bd6209f87dc7c6f56e2c0314e19f9cab95ec.

`SampleConsensusModelStick` is very similar to `SampleConsensusModelLine` (but broken as detailed #2452 since I still haven't figured out what to do with the radius model parameter there :sweat: :man_facepalming:) but hasn't received the changes of 36c2bd6209f87dc7c6f56e2c0314e19f9cab95ec.

`SampleConsensusModelCylinder` on the other hand doesn't do that kind of point dissimilarity validation in [`isSamplesGood(...)`](https://github.com/PointCloudLibrary/pcl/blob/6db82661ca1a19cabc785faf7b2d6d41b7483dcc/sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp#L51) at all and leaves it up to `computeModelCoefficients(...)`. The implementation in `computeModelCoefficients(...)` then is virtually identical to that of `SampleConsensusModelLine`.

If I managed to track down the usage of those functions correctly, they are used in `computeModel(...)` (`isSampleGood(...)` indirectly through `getSamples(...)`) of the various classes derived from [`SampleConsensus`](https://github.com/PointCloudLibrary/pcl/blob/6db82661ca1a19cabc785faf7b2d6d41b7483dcc/sample_consensus/include/pcl/sample_consensus/sac.h#L60) (e.g. [`RandomSampleConsensus`](https://github.com/PointCloudLibrary/pcl/blob/6db82661ca1a19cabc785faf7b2d6d41b7483dcc/sample_consensus/include/pcl/sample_consensus/impl/ransac.hpp#L57)) so for "practical" cases where those points really come from a sensor, there should not be much difference in the actual outcome. In some edge cases the log messages will likely differ since the validation fails in different portions of the algorithm.

**Context**

Real-time point cloud segmentation using RANSAC and the models above.

**Expected behavior**

Since these three models have quite some similarity, I would expect similar behavior of them.

**Current Behavior**

See description.

**To Reproduce**

Since this is a bug found by code analysis, you have to look at the code to reproduce my journey :wink: 

**Screenshots/Code snippets**

Links to some of the relevant code pieces are included in the description.

**Your Environment (please complete the following information):**

 - OS: Linux Mint 19.3
 - Compiler: GCC 7.5.4
 - PCL Version master (6db82661ca1a19cabc785faf7b2d6d41b7483dcc)

**Possible Solution**

If there is a consensus which of the validations (i.e. `abs` vs. `!=`, `&&` vs. `||`) is "the right one" and where it should live (`isSampleGood` vs. `computeModelCoefficients`), I think I could contribute a PR. My gut feeling goes towards something like

```cpp
if (
    std::abs ((*input_)[samples[0]].x - (*input_)[samples[1]].x) > std::numeric_limits<float>::epsilon ()
  ||
    std::abs ((*input_)[samples[0]].y - (*input_)[samples[1]].y) > std::numeric_limits<float>::epsilon ()
  ||
    std::abs ((*input_)[samples[0]].z - (*input_)[samples[1]].z) > std::numeric_limits<float>::epsilon ())
{
  return (true);
}
```

 in `isSampeGood(...)`. `std::abs` feels "more correct" than `!=` for floating points, but is more expensive to compute.

**Additional context**

-/-

### PR DESCRIPTION
**Pull request by alexvorndran**
Address inconsistencies in sample validation of
- [x] SampleConsensusModelLine
- [x] SampleConsensusModelCylinder
- [x] SampleConsensusModelCone
- [x] SampleConsensusModelPlane
- [x] SampleConsensusModelCircle2D
- [x] SampleConsensusModelCircle3D
- [x] ~~SampleConsensusModelStick~~ → might better be part of a fix for #2452

Resolves #5268.

### CODE REVIEW

**Comment by alexvorndran** [comment]
I also drafted a fix for #2452 including a few test cases based on 13a7946b53d019322accf23ac952dc6c15e9c3ce, but that might better fit into a separate PR since this touches more parts of the code.

File: test/sample_consensus/test_sample_consensus_line_models.cpp [hunk 1]
```diff
@@ -149,6 +149,88 @@ TEST (SampleConsensusModelLine, OnGroundPlane)
...
+TEST (SampleConsensusModelLine, SampleValidationPointsEqual)
+{
+  PointCloud<PointXYZ> cloud;
+  cloud.resize (2);
+
+  cloud[0].getVector3fMap () <<  0.1f,  0.0f,  0.0f;
+  cloud[1].getVector3fMap () <<  0.1f,  0.0f,  0.0f;
+
+  const auto previous_verbosity_level = pcl::console::getVerbosityLevel();
+  pcl::console::setVerbosityLevel(pcl::console::L_VERBOSE);
```
Comment (mvieth) [inline test/sample_consensus/test_sample_consensus_line_models.cpp:161]: This should usually not be necessary, or do you have a specific reason to add this?
We did this at on place because a test sometimes failed randomly on the CI, but always ran successfully locally. If there is no reason to assume that this test might fail, it would just add unnecessary output

Comment (alexvorndran) [reply test/sample_consensus/test_sample_consensus_line_models.cpp:161]: The main reason I did this was to get/give an idea of the changed log output. The checks are now only implemented in `isSampleGood` which is then called from `computeModelCoefficients`. That implementation detail is leaked by the log messages. I don't know if that's a real issue or not.

File: sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp [hunk 2]
```diff
@@ -55,16 +55,28 @@ pcl::SampleConsensusModelCylinder<PointT, PointNT>::isSampleGood (const Indices
...
 template <typename PointT, typename PointNT> bool
 pcl::SampleConsensusModelCylinder<PointT, PointNT>::computeModelCoefficients (
       const Indices &samples, Eigen::VectorXf &model_coefficients) const
 {
-  // Need 2 samples
-  if (samples.size () != sample_size_)
+  // Make sure that the samples are valid
+  if (!isSampleGood (samples))
   {
     PCL_ERROR ("[pcl::SampleConsensusModelCylinder::computeModelCoefficients] Invalid set of samples given (%lu)!\n", samples.size ());
```
[the remark this answers is not in the document]
Comment (alexvorndran) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp:81]: Sure.

Am I correct in my interpretation of the contribution guidelines that it's preferred to have a clean commit history, i.e. squash your recommended changes into the existing commits?

[the remark this answers is not in the document]
Comment (mvieth) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp:81]: During the reviewing process it is usually clearer when new changes are added as new commits. When we are all happy with the changes, we can think about cleaning up the commit history by squashing some commits, or squash _all_ commits into a single commit when merging

[the remark this answers is not in the document]
Comment (alexvorndran) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp:81]: What do you think of "inverting" the similarity condition so that control flow of `isSampleGood` is more "symmetric"? Now (or soon to be):

```cpp
template <typename PointT> bool
pcl::SampleConsensusModelLine<PointT>::isSampleGood (const Indices &samples) const
{
  if (samples.size () != sample_size_)
  {
    PCL_ERROR ("[pcl::SampleConsensusModelLine::isSampleGood] Wrong number of samples (is %lu, should be %lu)!\n", samples.size (), sample_size_);
    return (false);
  }

  // Make sure that the two sample points are not identical
  if (
      std::abs ((*input_)[samples[0]].x - (*input_)[samples[1]].x) > std::numeric_limits<float>::epsilon ()
    ||
      std::abs ((*input_)[samples[0]].y - (*input_)[samples[1]].y) > std::numeric_limits<float>::epsilon ()
    ||
      std::abs ((*input_)[samples[0]].z - (*input_)[samples[1]].z) > std::numeric_limits<float>::epsilon ())
  {
    return (true);
  }

  PCL_ERROR ("[pcl::SampleConsensusModelLine::isSampleGood] The two sample points are too similar!\n");
  return (false);
}
```

vs.

```cpp
template <typename PointT> bool
pcl::SampleConsensusModelLine<PointT>::isSampleGood (const Indices &samples) const
{
  if (samples.size () != sample_size_)
  {
    PCL_ERROR ("[pcl::SampleConsensusModelLine::isSampleGood] Wrong number of samples (is %lu, should be %lu)!\n", samples.size (), sample_size_);
    return (false);
  }

  // Make sure that the two sample points are not identical
  if (
      std::abs ((*input_)[samples[0]].x - (*input_)[samples[1]].x) <= std::numeric_limits<float>::epsilon ()
    &&
      std::abs ((*input_)[samples[0]].y - (*input_)[samples[1]].y) <= std::numeric_limits<float>::epsilon ()
    &&
      std::abs ((*input_)[samples[0]].z - (*input_)[samples[1]].z) <= std::numeric_limits<float>::epsilon ())
  {
    PCL_ERROR ("[pcl::SampleConsensusModelLine::isSampleGood] The two sample points are too similar!\n");
    return (false);
  }

  return (true);
}
```

[the remark this answers is not in the document]
Comment (mvieth) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp:81]: Sounds good!

File: sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp [hunk 3]
```diff
@@ -297,12 +302,12 @@ pcl::SampleConsensusModelCylinder<PointT, PointNT>::optimizeModelCoefficients (
   Eigen::NumericalDiff<OptimizationFunctor > num_diff (functor);
   Eigen::LevenbergMarquardt<Eigen::NumericalDiff<OptimizationFunctor>, float> lm (num_diff);
   int info = lm.minimize (optimized_coefficients);
-  
+
```
[the remark this answers is not in the document]
Comment (alexvorndran) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp]: Tried my best to revert these changes for now in 7743077ce5101c9be46f88e80d42bd7cb4140a5f.

File: sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (alexvorndran) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp]: A side effect of this is that the test `SampleConsensusModelLine.SampleValidationPointsEqual` now got a verbose even without the manually increased verbosity level since in the test case this branch is hit every time until the iteration count is exhausted (1000x if i'm not mistaken).

File: test/sample_consensus/test_sample_consensus_line_models.cpp [hunk 4]
```diff
@@ -149,6 +149,73 @@ TEST (SampleConsensusModelLine, OnGroundPlane)
...
+  cloud[0].getVector3fMap () <<  0.1f,  0.0f,  0.0f;
+  cloud[1].getVector3fMap () <<  0.1f,  0.0f,  0.0f;
+
+  // Create a shared line model pointer directly
+  SampleConsensusModelLinePtr model (new SampleConsensusModelLine<PointXYZ> (cloud.makeShared ()));
+
+  // Algorithm tests
+  pcl::Indices samples;
+  int iterations = 0;
+  model->getSamples(iterations, samples);
```
Comment (mvieth) [inline test/sample_consensus/test_sample_consensus_line_models.cpp:166]: I think having the same error message 1000 times in the test log is not so nice. How about changing this test by adding a third point unequal to the other two, and checking that this third point is in the sample?
Otherwise the changes look good :smile:

Comment (alexvorndran) [reply test/sample_consensus/test_sample_consensus_line_models.cpp:166]: Wouldn't that open up the possibility that the third point is selected on the first run by pure chance so the branch that this is supposed to test doesn't get exercised? That part of my brain got a little bit rusty, but if I'm not mistaken that could actually happen in 2 out of 3 cases (ignoring sample order).

Would it instead be an option to decrease the max. iteration count to something like 10 (technically one iteration would be sufficient, I guess :laughing:)?

Comment (mvieth) [reply test/sample_consensus/test_sample_consensus_line_models.cpp:166]: That would depend on the random number generation, especially the seed. By default, the behaviour is deterministic and the seed is always the same. So we should be able to find a configuration where that branch is always executed. Maybe the order of the points has to be switched (so that the "unequal" point is either at the beginning, or in the middle, or at the end). If we see that error message at least once in the test log, then we have a good configuration.
I also considered changing the max. number of iterations (`max_sample_checks_`), but that variable is `static const` with no way to change it from outside, and I would prefer to leave it at 1000.

Comment (alexvorndran) [reply test/sample_consensus/test_sample_consensus_line_models.cpp:166]: I likely had `setMaxIterations` of `SampleConsensus` in my mind, but of course we are in `SampleConsensusModel` here.

Parts of the test code below likely scream "DON'T!" right in your face, but I think that's about it what we can do here. Asserting on stdout/stderr does seem to be a [touchy topic](https://stackoverflow.com/a/33186201/) in googletest :laughing: Unfortunately It also doesn't work to assert on `iterations` being at least 2, since it is only set when there are not enough samples to draw from.

```cpp
TEST (SampleConsensusModelLine, SampleValidationPointsEqual)
{
  PointCloud<PointXYZ> cloud;
  cloud.resize (3);

  // The "cheat point" makes it possible to find a set of valid samples and
  // therefore avoids the log messages of an unsuccessful sample validation
  // being printed a 1000 times without any chance of success.
  // The order is chosen such that with a known, fixed rng-state/-seed all
  // validation steps are actually exercised.
  const pcl::index_t firstKnownEqualPoint = 0;
  const pcl::index_t secondKnownEqualPoint = 1;
  const pcl::index_t cheatPointIndex = 2;

  cloud[firstKnownEqualPoint].getVector3fMap () <<  0.1f,  0.0f,  0.0f;
  cloud[secondKnownEqualPoint].getVector3fMap () <<  0.1f,  0.0f,  0.0f;
  cloud[cheatPointIndex].getVector3fMap () <<  0.0f,  0.1f,  0.0f; // <-- cheat point

  // Create a shared line model pointer directly
  SampleConsensusModelLinePtr model (new SampleConsensusModelLine<PointXYZ> (cloud.makeShared ()));

  // Algorithm tests
  pcl::Indices samples;
  int iterations = 0;
  model->getSamples(iterations, samples);
  // The best option would be to assert on stderr output here, but that doesn't
  // seem to be that simple.
  EXPECT_EQ (samples.size(), 2);
  // The "cheat point" has to be part of the sample, otherwise something is wrong
  EXPECT_TRUE (std::find(samples.begin (), samples.end (), cheatPointIndex) != samples.end ());

  pcl::Indices forcedSamples = {firstKnownEqualPoint, secondKnownEqualPoint};
  Eigen::VectorXf modelCoefficients;
  EXPECT_FALSE (model->computeModelCoefficients (forcedSamples, modelCoefficients));
}
```

Comment (mvieth) [reply test/sample_consensus/test_sample_consensus_line_models.cpp:166]: Looks good. Maybe another comment that `model` is on purpose called with the default `random = false`

Comment (alexvorndran) [reply test/sample_consensus/test_sample_consensus_line_models.cpp:166]: I could also imagine going a step further and being even more explicit:
```cpp
// Create a shared line model pointer directly and explicitly disable the
// random seed for the reasons mentioned above
SampleConsensusModelLinePtr model (
  new SampleConsensusModelLine<PointXYZ> (cloud.makeShared (), /* random = */ false));
```
Just from some grep-ing, that "fake named argument" thing doesn't seem to be used widely in PCL.

File: test/sample_consensus/test_sample_consensus_line_models.cpp [hunk 5]
```diff
@@ -149,6 +149,89 @@ TEST (SampleConsensusModelLine, OnGroundPlane)
...
+  EXPECT_EQ (samples.size(), 2);
+
+  pcl::Indices forcedSamples = {0, 1};
```
Comment (alexvorndran) [inline test/sample_consensus/test_sample_consensus_line_models.cpp:209]: To discuss: Replace `forcedSamples` here with `samples` return value from `getSamples`. That would serve as a bonus test for the proper interaction between `getSamples`, too.

```cpp
Eigen::VectorXf modelCoefficients;
EXPECT_TRUE (model->computeModelCoefficients (samples, modelCoefficients));
```

Depending on the decision either this piece of code or the corresponding piece in the plane tests (61c9ee57745b5942f1061f58682f37e70f29d02a) needs to be adapted.

File: sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle.hpp [hunk 6]
```diff
@@ -64,19 +64,23 @@ pcl::SampleConsensusModelCircle2D<PointT>::isSampleGood(const Indices &samples)
   // Compute the segment values (in 2d) between p2 and p0
   p2 -= p0;
 
-  Eigen::Array2d dy1dy2 = p1 / p2;
+  // Check if the triangle area spanned by the three sample points is greater than 0
+  // https://en.wikipedia.org/wiki/Triangle#Using_vectors
+  if (std::abs (p1.x()*p2.y() - p2.x()*p1.y()) <= std::numeric_limits<double>::epsilon ()) {
```
[the remark this answers is not in the document]
Comment (alexvorndran) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle.hpp:69]: Yeah, I guess 2e-16 is probably too low. Eigen itself uses a self-defined `dummy_precision` ([1e-5 for float](https://gitlab.com/libeigen/eigen/-/blob/d49ede4dc4203942c2e01a7b39f23f2d9710765e/Eigen/src/Core/NumTraits.h#L237), [1e-12 for double](https://gitlab.com/libeigen/eigen/-/blob/d49ede4dc4203942c2e01a7b39f23f2d9710765e/Eigen/src/Core/NumTraits.h#L243)) as default, e.g. in [`isZero()`](https://gitlab.com/libeigen/eigen/-/blob/d49ede4dc4203942c2e01a7b39f23f2d9710765e/Eigen/src/Core/DenseBase.h#L376). So maybe that's something to make use of?

Otherwise something between 1e-5 and 1e-7 could be the way to go. 1e-5/1e-6 would leave about two/one order(s) of magnitude of margin to compute something with floats and ample margin for double :laughing:

[the remark this answers is not in the document]
Comment (mvieth) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle.hpp:69]: Right, `dummy_precision` is also an option. Let's use that.
BTW let's try to not make this PR much bigger. The bigger, the more difficult it is to review and the longer it takes. If there are many more changes you want to make, maybe consider creating another PR for that?

[the remark this answers is not in the document]
Comment (alexvorndran) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle.hpp:69]: Sorry to bother you once again, but would you like to see`Eigen::NumTraits<double>::dummy_precision ()` or `Eigen::NumTraits<float>::dummy_precision ()` here (and in Circle3D)?

With Circle and Circle3D, this should be fairly "complete" from what I can contribute. The only thing I could offer is to change the checks in the other models from `std::numeric_limits<float>::epsilon ()` to `Eigen::NumTraits<double>::dummy_precision ()` as well, but that's about it.

Other than that, please let me know if you want the commits to be squashed (e.g. per model) or if you want to do squash-merge all of them. (And before I forget: thanks for your patience sticking with me on this adventure so far.)

[the remark this answers is not in the document]
Comment (mvieth) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle.hpp:69]: > Sorry to bother you once again, but would you like to see`Eigen::NumTraits<double>::dummy_precision ()` or `Eigen::NumTraits<float>::dummy_precision ()` here (and in Circle3D)?

Hm, difficult to decide. Maybe double, if all computation in `isSampleGood` and `computeModelCoefficients` is in double (1e-12 seems reasonable then), else float?

> With Circle and Circle3D, this should be fairly "complete" from what I can contribute. The only thing I could offer is to change the checks in the other models from `std::numeric_limits<float>::epsilon ()` to `Eigen::NumTraits<double>::dummy_precision ()` as well, but that's about it.

I would say changing from epsilon to dummy_precision everywhere is not necessary if we are not changing those code parts anyway.

> Other than that, please let me know if you want the commits to be squashed (e.g. per model) or if you want to do squash-merge all of them. (And before I forget: thanks for your patience sticking with me on this adventure so far.)

One commit with the new tests, one commit with the changes in sample_consensus/* would be nice. Thank you for your contribution!

File: sample_consensus/include/pcl/sample_consensus/impl/sac_model_plane.hpp [hunk 7]
```diff
@@ -55,58 +55,63 @@ pcl::SampleConsensusModelPlane<PointT>::isSampleGood (const Indices &samples) co
...
   }
 
   // Compute the plane coefficients from the 3 given points in a straightforward manner
   // calculate the plane normal n = (p2-p1) x (p3-p1) = cross (p2-p1, p3-p1)
   model_coefficients.resize (model_size_);
-  model_coefficients[0] = p1p0[1] * p2p0[2] - p1p0[2] * p2p0[1];
-  model_coefficients[1] = p1p0[2] * p2p0[0] - p1p0[0] * p2p0[2];
-  model_coefficients[2] = p1p0[0] * p2p0[1] - p1p0[1] * p2p0[0];
+  model_coefficients.template head<3>() = cross / crossNorm;
   model_coefficients[3] = 0.0f;
```
Comment (mvieth) [inline sample_consensus/include/pcl/sample_consensus/impl/sac_model_plane.hpp:111]: If we don't call `normalize()` afterwards, setting this to 0 is not needed any more

File: test/sample_consensus/test_sample_consensus_quadric_models.cpp [hunk 8]
```diff
@@ -636,7 +719,7 @@ TEST (SampleConsensusModelCircle3D, RANSAC)
   EXPECT_NEAR (-3.0, coeff[2], 1e-3);
   EXPECT_NEAR ( 0.1, coeff[3], 1e-3);
   EXPECT_NEAR ( 0.0, coeff[4], 1e-3);
-  EXPECT_NEAR (-1.0, coeff[5], 1e-3);
+  EXPECT_NEAR ( 1.0, coeff[5], 1e-3);
```
Comment (mvieth) [inline test/sample_consensus/test_sample_consensus_quadric_models.cpp:722]: Let's put `std::abs(coeff[5])` here? Same below for refined. For other seeds, the algorithm could as well return `[0, -1, 0]`  as a normal, which would also be valid.

Comment (alexvorndran) [reply test/sample_consensus/test_sample_consensus_quadric_models.cpp:722]: Any preferences how to align them after `std::abs` is in place? Or are you fine with a little "bump"?

```cpp
  EXPECT_NEAR ( 1.0, coeff[0], 1e-3);
  EXPECT_NEAR ( 5.0, coeff[1], 1e-3);
  EXPECT_NEAR (-3.0, coeff[2], 1e-3);
  EXPECT_NEAR ( 0.1, coeff[3], 1e-3);
  EXPECT_NEAR ( 0.0, coeff[4], 1e-3);
  EXPECT_NEAR ( 1.0, std::abs (coeff[5]), 1e-3);
  EXPECT_NEAR ( 0.0, coeff[6], 1e-3);
```

Comment (mvieth) [reply test/sample_consensus/test_sample_consensus_quadric_models.cpp:722]: Yeah, that's fine :+1:

File: sample_consensus/include/pcl/sample_consensus/impl/sac_model_plane.hpp [hunk 9]
```diff
@@ -55,58 +55,62 @@ pcl::SampleConsensusModelPlane<PointT>::isSampleGood (const Indices &samples) co
...
+  pcl::Vector3fMapConst p0 = (*input_)[samples[0]].getVector3fMap ();
+  pcl::Vector3fMapConst p1 = (*input_)[samples[1]].getVector3fMap ();
+  pcl::Vector3fMapConst p2 = (*input_)[samples[2]].getVector3fMap ();
 
-  // Compute the segment values (in 3d) between p1 and p0
-  Eigen::Array4f p1p0 = p1 - p0;
-  // Compute the segment values (in 3d) between p2 and p0
-  Eigen::Array4f p2p0 = p2 - p0;
+  const Eigen::Vector3f cross = (p1 - p0).cross(p2 - p0);
+  const float crossNorm = cross.stableNorm();
```
Comment (mvieth) [inline sample_consensus/include/pcl/sample_consensus/impl/sac_model_plane.hpp:98]: Another thing (sorry -- this is probably my last complaint :wink: ): Is it possible that we get problems with `stableNorm()`? [The documentation](https://eigen.tuxfamily.org/dox/classEigen_1_1MatrixBase.html#title88) says that it divides by the largest coefficient. Isn't it possible that is zero, e.g. when all three points are the same? What was your motivation to choose `stableNorm()` over `norm()`? Admittedly, "stable" sounds good on first look :smile:

Comment (alexvorndran) [reply sample_consensus/include/pcl/sample_consensus/impl/sac_model_plane.hpp:98]: Eigen seems<sup>1</sup> to be clever enough not to blow up in that case as shown here:

```cpp
#include <iostream>

#include <Eigen/Eigen>

int main(int argc, char* argv[])
{
	auto vec = Eigen::Vector3f::Zero();
	std::cout << "vec.stableNorm() = " << vec.stableNorm() << std::endl;
}
```
yields
```
vec.stableNorm() = 0
```

-----

<sup>1</sup> I also checked the implementation, but I'm not a 100% sure if I followed the control flow correctly. If we assume that to be true, there is a condition that catches this case.

**Review by mvieth — APPROVED** [review]
Thank you for your contribution!
I will wait a few more days before merging, in case someone else wants to have a look.
