### PR TITLE
PLY face definition accepts uint fields as well

### LINKED ISSUE #4491: [io] not support uint as scalar type
**Describe the bug**

 This test will fail:

```cpp
TEST (PCL, PLYPolygonMeshUintIndices)
{
  std::ofstream fs;
  fs.open ("mesh_uint_indices.ply");
  fs <<
    "ply\n"
    "format ascii 1.0\n"
    "element vertex 3\n"
    "property float x\n"
    "property float y\n"
    "property float z\n"
    "element face 1\n"
    "property list uchar uint vertex_indices\n"
    "end_header\n"
    "0.0 0.0 0.0\n"
    "1.0 0.0 0.0\n"
    "1.0 1.1 0.0\n"
    "3 2 0 1\n";
  fs.close();
  pcl::PolygonMesh mesh;
  pcl::io::loadPLYFile("mesh_uint_indices.ply", mesh);
  EXPECT_EQ (mesh.polygons.front().vertices.size(), 3);
  remove("mesh_uint_indices.ply");
}
```

with messages:

```
[pcl::PLYReader] mesh_uint_indices.ply:8: property 'list uint8 uint32 vertex_indices' of element 'face' is not handled
/home/ros/tmp/pcl/test/io/test_ply_mesh_io.cpp:308: Failure
      Expected: mesh.polygons.front().vertices.size()
      Which is: 0
To be equal to: 3
```

This bug was already described in issue #2958.
Unfortunately, invalid behavior with face parsing are still actual.

**Possible Solution**

In function `pcl::PLYReader::parse(const std::string&)` add line:
```cpp
pcl::io::ply::ply_parser::at<pcl::io::ply::uint8, pcl::io::ply::uint32> (list_property_definition_callbacks) =
  [this] (const std::string& element_name, const std::string& property_name)
  {
    return 
      listPropertyDefinitionCallback<pcl::io::ply::uint8, pcl::io::ply::int32>
        (element_name, property_name);
  }
```

Implementation for parsing `property list` exists only for pair `<uin8, int32>`. Cause indices are usually less than `2^31`, conflicts with negative indices will not happen.

### PR DESCRIPTION
**Pull request by DaniilSNikulin**
fixes #4491

### CODE REVIEW

File: io/src/ply_io.cpp [hunk 1]
```diff
@@ -543,6 +543,7 @@ pcl::PLYReader::parse (const std::string& istream_filename)
 
   pcl::io::ply::ply_parser::list_property_definition_callbacks_type list_property_definition_callbacks;
   pcl::io::ply::ply_parser::at<pcl::io::ply::uint8, pcl::io::ply::int32> (list_property_definition_callbacks) = [this] (const std::string& element_name, const std::string& property_name) { return listPropertyDefinitionCallback<pcl::io::ply::uint8, pcl::io::ply::int32> (element_name, property_name); };
+  pcl::io::ply::ply_parser::at<pcl::io::ply::uint8, pcl::io::ply::uint32> (list_property_definition_callbacks) = [this] (const std::string& element_name, const std::string& property_name) { return listPropertyDefinitionCallback<pcl::io::ply::uint8, pcl::io::ply::int32> (element_name, property_name); };
```
Comment (kunaltyagi) [inline io/src/ply_io.cpp:546]: Oof. I can see a  few combinations missing... but this changeset LGTM

**Review by kunaltyagi — APPROVED** [review]

**Comment by kunaltyagi** [comment]
Please edit the title as needed

Is this a fix or an enhancement? Marked as enhancement, but feels like a fix

**Comment by DaniilSNikulin** [comment]
> Is this a fix or an enhancement? Marked as enhancement, but feels like a fix

I suppose this PR more likely is fix. PLY file format allow using `uint` for indices. So lack of support this case looks like a bug.

File: io/src/ply_io.cpp (hunk 1 above)
Comment (mvieth) [reply io/src/ply_io.cpp:546]: I am not that familiar with the PLY reader/parser, so just to be sure: the `int32` near the end is not supposed to be `uint32`?

Comment (DaniilSNikulin) [reply io/src/ply_io.cpp:546]: Yes, if  index will be more than `2^31`, than `int32` will be negative and `uint32` will not.
I think, this case are unlikely. The size of cloud must be more than 25GB. In addition if `pcl::index_t` == `int32`, so pcl can't read this cloud to `pcl::PolygonMesh` in any case.

Comment (larshg) [reply io/src/ply_io.cpp:546]: Its just that there is **uint32** in `at<pcl::io::ply::uint8, pcl::io::ply::uint32>` at the beginning and **int32** in `listPropertyDefinitionCallback<pcl::io::ply::uint8, pcl::io::ply::int32>` at the end of line.

Shouldn't they either be **int32**  or **uint32** at both places?

Comment (DaniilSNikulin) [reply io/src/ply_io.cpp:546]: As described in #4491, implementation for parsing `property list` exists only for pair `<uin8, int32>`

Function declaration looks like this:
```cpp
 /** \brief function called when a list property is parsed
   * \param[in] element_name element name to which the property belongs
   * \param[in] property_name list property name
   */
 template <typename SizeType, typename ScalarType>
 std::tuple<std::function<void (SizeType)>, std::function<void (ScalarType)>, std::function<void ()> >
 listPropertyDefinitionCallback (const std::string& element_name, const std::string& property_name);
```
I could replace implementation `<uin8, int32>` by specialization `<uint8, std::numeric_limits<T>::is_integer>`.
Specialization will be looks like this:
```cpp
template <typename SizeType, typename ScalarType>
typename std::enable_if<
    std::is_same<pcl::io::ply::uint8, SizeType>::value && std::numeric_limits<ScalarType>::is_integer,
    std::tuple<std::function<void (SizeType)>, std::function<void (ScalarType)>, std::function<void ()> >
>::type
listPropertyDefinitionCallback (const std::string& element_name, const std::string& property_name);
```
Is this will be better?

Comment (larshg) [reply io/src/ply_io.cpp:546]: I'm just puzzled why its not unit32 both places - but lets just keep your current implementation.

**Review by larshg — APPROVED** [review]
