### PR TITLE
Fix function signature mismatching.

### LINKED ISSUE #1624: pcl::io::save signature mismatching.
The function template pcl::io::save has a distinct signature on [declaration](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/auto_io.h#L102)  and [definition](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/impl/auto_io.hpp#L75).
Any code using that function won't compile.

### PR DESCRIPTION
**Pull request by renatoGarcia**
Fix #1624 

The function template pcl::io::save has a distinct signature on
declaration (pcl/io/auto_io.h) and definition (pcl/io/impl/auto_io.hpp).

On fixing that a bug popup on ifs_io.h. The conversion order between
PointCloud<> to/from PCLPointCloud2 was backward.

### CODE REVIEW

File: test/io/test_io.cpp [hunk 1]
```diff
@@ -1365,6 +1366,36 @@ TEST (PCL, Locale)
 #endif
 }
 
+//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
+TEST (PCL, AutoIO)
```
Comment (SergioRAgostinho) [inline test/io/test_io.cpp]: Since you're working with a ```PointCloud<PointT>``` type, i would recommend you write a typed test case like [this](https://github.com/renatoGarcia/pcl/blob/0a0bdb9c7e146583a7ed32230e6f28f5a2ee84d4/test/io/test_io.cpp#L1017-L1020) but for all point types. The macro is ```PCL_POINT_TYPES```.

File: test/io/test_io.cpp [hunk 2]
```diff
@@ -1365,6 +1366,36 @@ TEST (PCL, Locale)
...
+
+  cloud.width  = 640;
+  cloud.height = 480;
+  cloud.resize (cloud.width * cloud.height);
+  cloud.is_dense = true;
+
+  save ("test_autoio.pcd", cloud);
+  save ("test_autoio.ply", cloud);
+  save ("test_autoio.ifs", cloud);
+
```
Comment (SergioRAgostinho) [inline test/io/test_io.cpp]: I'm not really fond of dumping stuff into the disk and not cleaning up after. Can you erase these files upon exiting the test?

**Comment by renatoGarcia** [comment]
I have implemented your suggestions, but there are errors arising when loading a .ply file for some point types. These errors are on functions that load the ply file, not on pcl::io::save() or pcl::io::load() that only route the call accordingly to a file extension.

For now I would suggest simply comment out the ply tests, as that doesn't invalidates nor is directly related to the bug being fixed by this PR.

File: test/io/test_io.cpp [hunk 3]
```diff
@@ -1365,6 +1366,43 @@ TEST (PCL, Locale)
 #endif
 }
 
+//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
+template <typename T> class AutoIOTest : public testing::Test { };
+typedef ::testing::Types<BOOST_PP_SEQ_ENUM (PCL_POINT_TYPES)> PCLPointTypes;
```
Comment (SergioRAgostinho) [inline test/io/test_io.cpp]: Change this to 
```c++
typedef ::testing::Types<BOOST_PP_SEQ_ENUM (PCL_XYZ_POINT_TYPES PCL_NORMAL_POINT_TYPES)> PCLPointTypes;
```

**Comment by SergioRAgostinho** [comment]
Implement the change on the point types I just mentioned, uncomment the PLY tests, squash the commits and I think we're good to go.

**Comment by SergioRAgostinho** [comment]
@jspricke Speaking of ABI breakage, what about this PR. We're changing the function signature, although it was wrong and not compiling so... Just want to be sure this should go on 1.8.1 :)

**Comment by renatoGarcia** [comment]
@SergioRAgostinho  Done with changes and squash.

**Comment by renatoGarcia** [comment]
@SergioRAgostinho @jspricke  As of API breakage, yes that could be a problem. Although in this function signature, as far as could search, the API has never worked to begin with. If I'm not wrong, the function was added in [ab0ecd](https://github.com/PointCloudLibrary/pcl/blob/ab0ecd70dad7f284243e28678492af8402368a51/io/include/pcl/io/file_io.h#L434) but only declaration, without a template function definition. The definition was added in [a6f157](https://github.com/PointCloudLibrary/pcl/blob/a6f157968de0c217b81e3a28b9e29b914f26ea6d/io/include/pcl/io/impl/file_io.hpp#L70), but already with the current argument mismatch.

**Comment by SergioRAgostinho** [comment]
Thanks! @VictorLamoine @taketwo opinions on this? 1.8.1 or 1.9.0? 
My reasoning is it should still go to 1.8.1 because the original function could not be even be used/compiled, ergo we're not exactly breaking anything.

**Comment by VictorLamoine** [comment]
`1.8.1`, I can't see how we could be breaking anyone's code with this PR.

**Comment by taketwo** [comment]
Agree.
