### PR TITLE
Remove assumptions (used while packaging PCL) for `getMatrixXfMap` documentation

### LINKED ISSUE #4770: [core] PointCloud::getMatrixXfMap() has incorrect documentation
[The doc](https://pointclouds.org/documentation/classpcl_1_1_point_cloud.html#ada3e021bcb3f4d8d62ea3f00324fc126) states 

> number of points in a cloud = rows in a matrix, number of point dimensions = columns in a matrix

However I have found this to be incorrect:
```
  PointCloud<PointXYZ>::Ptr p_in{new PointCloud<PointXYZ>};
  pcl::io::loadPCDFile("pcl/test/bunny.pcd", *p_in);
  const auto map = p_in->getMatrixXfMap(4, 4, 0);
  std::cout << map.rows() << ", " << map.cols() << std::endl;
```
The matrix has a shape of (4, 397), instead of (397, 4) as the documentation states.

### PR DESCRIPTION
**Pull request by kunaltyagi**
Closes #4770

### CODE REVIEW

File: common/include/pcl/point_cloud.h [hunk 1]
```diff
@@ -315,9 +315,12 @@ namespace pcl
       /** \brief Return an Eigen MatrixXf (assumes float values) mapped to the specified dimensions of the PointCloud.
         * \note This method is for advanced users only! Use with care!
         *
-        * \attention Since 1.4.0, Eigen matrices are forced to Row Major to increase the efficiency of the algorithms in PCL
-        *   This means that the behavior of getMatrixXfMap changed, and is now correctly mapping 1-1 with a PointCloud structure,
-        *   that is: number of points in a cloud = rows in a matrix, number of point dimensions = columns in a matrix
+        * \attention Comile time flags used for Eigen might affect the dimension of the Eigen::Map returned. If Eigen
```
Comment (mvieth) [inline common/include/pcl/point_cloud.h:318]: Comile -> Compile (same below)
I am not sure that there is a compile time flag that changes the default storage order, though? I think `Eigen::MatrixXf::Flags` is always set to col-major, unless the Eigen maintainers decide to change that for some reason?

Comment (kunaltyagi) [reply common/include/pcl/point_cloud.h:318]: Eigen is a head only library. So the flag needs to be present at compile time.

Comment (mvieth) [reply common/include/pcl/point_cloud.h]: I thought there was no flag/option to change the default storage order, but turns out there is: `EIGEN_DEFAULT_TO_ROW_MAJOR` ([described here](https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html))

**Review by larshg — APPROVED** [review]
