### PR TITLE
[fix] Improve error handling of `FittingSurface::initNurbsPCABoundingBox`

### LINKED ISSUE #6378: possible typo, checking v_max(0) > v_min(0) twice
**Describe the bug**

surface > src > on_nurbs > fitting_surface_pdm.cpp > InitNurbsPCABoundingBox(...) (line 501)
checks:
 if (v_max (0) > v_min (0) && v_max (0) > v_min (0))
makes more sense to check both (0) and (1):
 if (v_max (0) > v_min (0) && v_max (1) > v_min (1))

 - PCL Version [e.g. 1.15.1, HEAD]

(stumbled upon this while trying to understand the function.)

### PR DESCRIPTION
**Pull request by chunibyo-wly**
fix #6378

### CODE REVIEW

File: surface/src/on_nurbs/fitting_surface_pdm.cpp [hunk 1]
```diff
@@ -481,33 +481,17 @@ FittingSurface::initNurbsPCABoundingBox (int order, NurbsDataSurface *m_data, Ei
...
-    if (p (1) < v_min (1))
-      v_min (1) = p (1);
-    if (p (2) < v_min (2))
-      v_min (2) = p (2);
+    v_max = v_max.cwiseMax (p);
+    v_min = v_min.cwiseMin (p);
   }
 
-  for (unsigned i = 0; i < s; i++)
+  if (v_max (0) < v_min (0) || v_max (1) < v_min (1))
```
Comment (mvieth) [inline surface/src/on_nurbs/fitting_surface_pdm.cpp]: Thanks for the pull request! However I think this should either use `<=` or even something like `(v_max (0) - v_min (0)) < std::numeric_limits<double>::epsilon`

File: surface/src/on_nurbs/fitting_surface_pdm.cpp [hunk 2]
```diff
@@ -481,33 +481,19 @@ FittingSurface::initNurbsPCABoundingBox (int order, NurbsDataSurface *m_data, Ei
...
-      v_min (1) = p (1);
-    if (p (2) < v_min (2))
-      v_min (2) = p (2);
+    v_max = v_max.cwiseMax (p);
+    v_min = v_min.cwiseMin (p);
   }
 
-  for (unsigned i = 0; i < s; i++)
+  if (v_max(0) - v_min(0) < std::numeric_limits<double>::epsilon() ||
+      v_max(1) - v_min(1) < std::numeric_limits<double>::epsilon())
```
Comment (mvieth) [inline surface/src/on_nurbs/fitting_surface_pdm.cpp]: IMO, parentheses would make this clearer, but since subtraction is done before the comparison, the code is still correct.
