### PR TITLE
Fix PCL_DEPRECATED usage in doxygen for a proper Deprecation List in documentation

### LINKED ISSUE #3825: [CI] The deprecation list is showing weird things
The deprecation list is showing weird things on https://pointcloudlibrary.github.io/documentation/deprecated.html but not on http://docs.pointclouds.org/trunk/deprecated.html.

EDIT: and CI is reporting this
```
/__w/1/s/common/include/pcl/common/io.h:82: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/common/include/pcl/common/io.h:111: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/common/include/pcl/common/io.h:121: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/common/include/pcl/common/io.h:335: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/common/include/pcl/point_cloud.h:142: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/segmentation/include/pcl/segmentation/supervoxel_clustering.h:291: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
```
and more new ones

_Originally posted by @aPonza in https://github.com/PointCloudLibrary/pcl/pull/3808#issuecomment-605535873_

### PR DESCRIPTION
**Pull request by aPonza**
Close #3825

> So the error itself is because "." ends the period if [`JAVADOC_AUTOBRIEF`](http://www.doxygen.nl/manual/config.html#cfg_javadoc_autobrief)`= YES` so the solution is either to set it to `= NO` or escape the dot like `.\ ` (notice the trailing whitespace). In both cases the version number becomes "1 . 12" which is ugly and I think there is no solution to inserted whitespace since I found the unresolved [doxygen/doxygen#6154](https://github.com/doxygen/doxygen/issues/6154) bug report.

from https://github.com/PointCloudLibrary/pcl/issues/3825#issuecomment-612433423

I also added a sed invocation to deal with the whitespace, thanks Sergey.

### CODE REVIEW

File: registration/include/pcl/registration/correspondence_rejection_poly.h [hunk 1]
```diff
@@ -110,9 +110,9 @@ namespace pcl
           * \param[in] cloud a cloud containing XYZ data
           */
         inline void 
+        PCL_DEPRECATED(1, 12, "pcl::registration::CorrespondenceRejectorPoly::setInputCloud is deprecated. Please use setInputSource instead")
         setInputCloud (const PointCloudSourceConstPtr &cloud)
         {
-          PCL_WARN ("[pcl::registration::%s::setInputCloud] setInputCloud is deprecated. Please use setInputSource instead.\n",
                     getClassName ().c_str ());
```
Comment (aPonza) [inline registration/include/pcl/registration/correspondence_rejection_poly.h:116]: missed this

**Comment by aPonza** [comment]
The commits' names aren't sufficient to address the related-but-different scopes here? I'll split this up, sure.

I've had this for 3 iterations now, though:
```
Scanning dependencies of target test_organized_search
[ 45%] Building CXX object test/search/CMakeFiles/test_organized_search.dir/test_organized.cpp.o
/Users/runner/runners/2.165.2/work/1/s/visualization/src/pcl_visualizer.cpp:1936:1: error: 'deprecated' attribute cannot be applied to types
PCL_DEPRECATED(1, 12, "pcl::visualization::PCLVisualizer::updateCamera is deprecated, just re-rendering all scenes now.")
^
/Users/runner/runners/2.165.2/work/1/s/common/include/pcl/pcl_macros.h:122:17: note: expanded from macro 'PCL_DEPRECATED'
                PCL_DEPRECATED_MINOR(Minor,                             \
                ^
/Users/runner/runners/2.165.2/work/1/s/common/include/pcl/pcl_macros.h:108:17: note: expanded from macro 'PCL_DEPRECATED_MINOR'
                PCL_DEPRECATED_IMPL(Msg),           \
                ^
/Users/runner/runners/2.165.2/work/1/s/common/include/pcl/pcl_macros.h:89:42: note: expanded from macro 'PCL_DEPRECATED_IMPL'
  #define PCL_DEPRECATED_IMPL(message) [[deprecated(message)]]
                                         ^
```

Why doesn't it like the macro? I'll think about it in the morning.

File: visualization/src/pcl_visualizer.cpp [hunk 2]
```diff
@@ -1904,40 +1910,40 @@ pcl::visualization::PCLVisualizer::initCameraParameters ()
...
+PCLVisualizer::getCameraFile () const
 {
   return (style_->getCameraFile ());
 }
 
-/////////////////////////////////////////////////////////////////////////////////////////////
+
 void
-pcl::visualization::PCLVisualizer::updateCamera ()
+PCL_DEPRECATED(1, 12, "pcl::visualization::PCLVisualizer::updateCamera is deprecated, just re-rendering all scenes now.")
```
Comment (kunaltyagi) [inline visualization/src/pcl_visualizer.cpp:1936]: Deprecation needs to come before the return type. [Syntax](https://en.cppreference.com/w/cpp/language/attributes/deprecated)

Comment (aPonza) [reply visualization/src/pcl_visualizer.cpp]: Solved in 9fa4c161979027a0f3385e5ef163c33af1155276 in PR #3925

**Comment by aPonza** [comment]
I stashed the changes in visualizer as they'll most likely come around again while clang-doxy-ing [visualization]
