### PR TITLE
OctreeIterators special member revision

### LINKED ISSUE #2064: OctreeIteratorBase bug in comparison operators ==/!=
There is a bug in octree_iterator.h for the operator==() and operator!=() which can be found between the lines 136 and 151. 

The boolean output of operator==() is inequal to the negation of the boolean output of operator!=(). 

## Your Environment

* Operating System and version: All
* Compiler: All
* PCL Version: Latest ( and most likely all previous ones ) 

## Expected Behavior
`(itA==itB) == !(itA!=itB);`

## Current Behavior
`(itA==itB) != !(itA!=itB);`

## Possible Solution

A quick fix might be this ( at least with that the code below will work ). 
 

```cpp
        bool operator==(const OctreeIteratorBase& other) const
        {
             return !this->operator!=(other);
         }
```
However, the problem seems to be more deeply nested inside the implementation of OctreeIteratorBase. It appears wrong that with octree.breadth_end() we get an iterator which is not related at all to the underlying octree. In other words

```cpp
auto aIt = octreeA.breadth_end();
auto bIt = octreeB.breadth_end();
```
The members of iterator aIt and bIt are absolutely identical. 

## Code to Reproduce

```cpp
       // works as expected
	auto it = octree.breadth_begin();
	const auto it_end = octree.breadth_end();

	for (it; it != it_end; it++)
	{
		cout << "Hello" << endl;
	}
```

```cpp
       // stuck in an endless loop
	auto it = octree.breadth_begin();
	const auto it_end = octree.breadth_end();
        while (true)
	{
		if (it == it_end)
			break;
		else
			it++;
         }
```

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Revised the implementations of the following operators
- Copy constructors
- Copy assignment
- Destructors
- Equality
- Inequality

Added unit tests to validate all changes.

#1983 is meant to be applied after this one.

Edit: Fixes  #2064

### CODE REVIEW

File: octree/include/pcl/octree/octree_iterator.h [hunk 1]
```diff
@@ -384,11 +362,17 @@ namespace pcl
...
-        virtual
-        ~OctreeDepthFirstIterator ();
+        /** \brief Copy Constructor.
+         * \param[in] other Another OctreeDepthFirstIterator to copy from
+         */
+        OctreeDepthFirstIterator (const OctreeDepthFirstIterator& other)
+          : OctreeIteratorBase<OctreeT> (other)
+          , stack_ (other.stack_)
+        {
+          this->current_state_ = stack_.size()? &stack_.back() : NULL;
```
Comment (taketwo) [inline octree/include/pcl/octree/octree_iterator.h]: Style

Also, can you please explain why we inherit the state from other, i.e. `this->current_state_ = other.current_state_`?

File: octree/include/pcl/octree/octree_iterator.h [hunk 2]
```diff
@@ -470,9 +454,15 @@ namespace pcl
...
-        virtual
-        ~OctreeBreadthFirstIterator ();
+        /** \brief Copy Constructor.
+         * \param[in] other Another OctreeBreadthFirstIterator to copy from
+         */
+        OctreeBreadthFirstIterator (const OctreeBreadthFirstIterator& other)
+          : OctreeIteratorBase<OctreeT> (other)
+          , FIFO_ (other.FIFO_)
+        {
+          this->current_state_ = FIFO_.size()? &FIFO_.front () : NULL;
```
Comment (taketwo) [inline octree/include/pcl/octree/octree_iterator.h]: Style

**Comment by SergioRAgostinho** [comment]
> Did you try PCL.Octree_Test on your machine? Seems to segfault on Travis.

No. It was 4 am already when I pushed this. I just decided to let Travis do it's job over the night :)

**Comment by frozar** [comment]
If it may help, I use this line to compile octree test on my machine (it's quick enough to get the binary):
```bash
cmake -DPCL_ONLY_CORE_POINT_TYPES=ON -DPCL_NO_PRECOMPILE=ON -DBUILD_tools=OFF -DBUILD_examples=OFF -DBUILD_apps=OFF -DBUILD_2d=OFF -DBUILD_features=OFF -DBUILD_filters=OFF -DBUILD_geometry=OFF -DBUILD_io=OFF -DBUILD_kdtree=OFF -DBUILD_keypoints=OFF -DBUILD_ml=OFF -DBUILD_octree=ON -DBUILD_outofcore=OFF -DBUILD_people=OFF -DBUILD_recognition=OFF -DBUILD_registration=OFF -DBUILD_sample_consensus=OFFF -DBUILD_search=OFF -DBUILD_segmentation=OFF -DBUILD_simulation=OFF -DBUILD_stereo=OFF -DBUILD_surface=OFF -DBUILD_tracking=OFF -DBUILD_visualization=OFF -DBUILD_global_tests=ON -DBUILD_tests_2d=OFF -DBUILD_tests_common=OFF -DBUILD_tests_features=OFF -DBUILD_tests_filters=OFF -DBUILD_tests_geometry=OFF -DBUILD_tests_io=OFF -DBUILD_tests_kdtree=OFF -DBUILD_tests_keypoints=OFF -DBUILD_tests_octree=ON -DBUILD_tests_outofcore=OFF -DBUILD_tests_people=OFF -DBUILD_tests_recognition=OFF -DBUILD_tests_registration=OFF -DBUILD_tests_sample_consensus=OFF -DBUILD_tests_search=OFF -DBUILD_tests_segmentation=OFF -DBUILD_tests_surface=OFF -DBUILD_tests_visualization=OFF -DGTEST_INCLUDE_DIR=/home/frozar/soft/googletest/googletest/include -DGTEST_SRC_DIR=/home/frozar/soft/googletest/googletest -DCMAKE_BUILD_TYPE=Debug .. && make -j8 test_octree
```

File: octree/include/pcl/octree/octree_iterator.h (hunk 1 above)
Comment (SergioRAgostinho) [reply octree/include/pcl/octree/octree_iterator.h]: I'm gonna redirect you to the explanation I gave @frozar when I had a first look at the copy constructor fix he did. Let me know in case you need further clarification. Here's the link https://github.com/PointCloudLibrary/pcl/pull/1983#discussion_r154152023

The important point to remember is that `current_state_` points to an address, which is normally the back element of the stack or the front of the FIFO vector (depending on the type of iterator) and when you perform the copy, this pointer needs to be updated the equivalent element of the stack/fifo container your object has. Also notice that `current_state_` is not a direct pointer to an octree node. Hence it can't be simply copied.

Comment (taketwo) [reply octree/include/pcl/octree/octree_iterator.h]: Thanks, makes sense.

File: octree/include/pcl/octree/octree_iterator.h [hunk 3]
```diff
@@ -135,19 +114,18 @@ namespace pcl
          */
         bool operator==(const OctreeIteratorBase& other) const
         {
-          return (( octree_ ==other.octree_) &&
-                  ( current_state_ == other.current_state_) &&
-                  ( max_octree_depth_ == other.max_octree_depth_) );
+          return (this == &other) ||
+                    ((octree_ == other.octree_) &&
+                     (current_state_ == other.current_state_) &&
```
Comment (taketwo) [inline octree/include/pcl/octree/octree_iterator.h]: Then here we should dereference, right? Otherwise this is never true.
(Plus protection from dereferencing null pointer).

**Comment by SergioRAgostinho** [comment]
The end iterators we're being constructed in a defective manner. The moment, we wrote a "proper" iterator equivalence/inequality they started failing of course.

These latest changes fix #2064 as well. The PR now lacks tests for checking the newly defined begin/end operators. To be added later.

**Comment by taketwo** [comment]
> The PR now lacks tests for checking the newly defined begin/end operators. To be added later.

In a separate PR? Should I merge this?

**Comment by SergioRAgostinho** [comment]
I’ll add on this PR.

**Comment by taketwo** [comment]
Can I just squash, or do you want to rearrange commits in some certain way?

**Comment by SergioRAgostinho** [comment]
I think I will squash  60c3272563dc716d6128de35902a134247c16cb9 into 44ffdd62ca32de5c0558e91e4cc0baf2ada0cd29 and then I think it would leave it like that.

**Comment by SergioRAgostinho** [comment]
Squashed and rebased on top of master for that additional appveyor checkup.

**Comment by SergioRAgostinho** [comment]
Ok, scratch that. I think I will just make two commits:
- Copy ctor, assignment and other methods revision, plus test
- Begin/end iterator revision plus tests
