### PR TITLE
[common] Add `bool`, `std::{u}int64_t` as possible point field types

### LINKED ISSUE #1153: Using POINT_CLOUD_REGISTER_POINT_STRUCT with uint64_t does not work
I have a structure type I want to register as a PCL type, one of the elements of that structure is a `uint64_t`, it fails with the error

```
error: 'value' is not a member of 'pcl::traits::asEnum<long unsigned int>'
 POINT_CLOUD_REGISTER_POINT_STRUCT(...
```

I believe I have tracked the root cause in two files:
1. A few missing type specializations.
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/point_traits.h#L73
2. A missing enumeration:
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/PCLPointField.h#L27

Is there any great reason which uint64 types are not permitted as field types?  Is there any objection to them being added?  I can see that there are a few other locations which may need specialization...

### LINKED ISSUE #2565: Bool PointFieldTypes in PCLPointField
## Your Environment
* Operating System and version: Ubuntu 18.04
* Compiler: GCC 7
* PCL Version: Latest

## Context
I am trying to create a custom point type as shown in http://pointclouds.org/documentation/tutorials/adding_custom_ptype.php#how-to-add-a-new-pointt-type. I then realize it's not possible to create an element with type `bool`. After a little bit of tracking, I realize the reason is because in http://docs.pointclouds.org/1.8.1/_p_c_l_point_field_8h_source.html there is no `bool` in the PointFieldTypes. 

Is this because `bool` won't work due to some complex reasons or is it just someone has to simply submit a PR to add it?

### PR DESCRIPTION
**Pull request by kunaltyagi**
Closes #1153, closes #2565

### CODE REVIEW

**Comment by kunaltyagi** [comment]
`io/src/ply_io.cpp` uses `int` in both `sizeof` and test output. Adding int64 there would need discussion (or is unneeded). Also needed: feedback on tests: `test/io/test_io.cpp`

**Comment by kunaltyagi** [comment]
@mvieth Could you review this please?

File: io/src/pcd_io.cpp [hunk 1]
```diff
@@ -467,60 +467,31 @@ pcl::PCDReader::readBodyASCII (std::istream &fs, pcl::PCLPointCloud2 &cloud, int
         }
         for (unsigned int c = 0; c < cloud.fields[d].count; ++c)
         {
+#define COPY_STRING(CASE_LABEL)                                                          \
```
Comment (mvieth) [inline io/src/pcd_io.cpp:470]: Is there maybe a possibility to remove the `switch` completely and map directly from `cloud.fields[d].datatype` to the template parameter?

File: io/src/pcd_io.cpp [hunk 2]
```diff
@@ -1153,69 +1094,55 @@ pcl::PCDWriter::writeASCII (const std::string &file_name, const pcl::PCLPointClo
...
+        default:
+          PCL_WARN("[pcl::PCDWriter::writeASCII] Incorrect field data type specified "
+                   "(%d)!\n",
+                   cloud.fields[d].datatype);
+          break;
         }
+#undef COPY_VALUE
 
-        if (d < cloud.fields.size () - 1 || c < static_cast<int> (cloud.fields[d].count) - 1)
+        if (d < cloud.fields.size() - 1 ||
```
Comment (mvieth) [inline io/src/pcd_io.cpp:1137]: Braces `()` would be nice to make operator precedence clear

File: tools/transform_point_cloud.cpp [hunk 3]
```diff
@@ -205,33 +205,27 @@ scaleInPlace (pcl::PCLPointCloud2 &cloud, double* multiplier)
...
-      case pcl::PCLPointField::UINT32:
-        for (int i = 0; i < 3; ++i) multiply<std::uint32_t> (cloud, xyz_offset[i], multiplier[i]);
-        break;
-      case pcl::PCLPointField::FLOAT32:
-        for (int i = 0; i < 3; ++i) multiply<float> (cloud, xyz_offset[i], multiplier[i]);
-        break;
-      case pcl::PCLPointField::FLOAT64:
-        for (int i = 0; i < 3; ++i) multiply<double> (cloud, xyz_offset[i], multiplier[i]);
-        break;
+      MULTIPLY(pcl::PCLPointField::BOOL)
```
Comment (mvieth) [inline tools/transform_point_cloud.cpp:216]: Makes no sense for `bool`

**Review by mvieth — COMMENTED** [review]
Generally I feel like some new tests are needed, especially since `BOOL` would be the first non-numeric type.
Do I see it correctly that this only affects `PCLPointCloud2`, but not the templated `PointCloud`? Are conversions still possible?

File: io/src/pcd_io.cpp (hunk 1 above)
Comment (kunaltyagi) [reply io/src/pcd_io.cpp:470]: No. The datatype is runtime, while template is compile time. 😢

File: filters/include/pcl/filters/impl/conditional_removal.hpp [hunk 4]
```diff
@@ -525,60 +525,33 @@ pcl::PointDataAtOffset<PointT>::compare (const PointT& p, const double& val)
...
+  case CASE_LABEL: {                                                                   \
+    pcl::traits::asType_t<CASE_LABEL> pt_val;                                          \
+    memcpy(&pt_val, pt_data + this->offset_, sizeof(pt_val));                          \
+    return (pt_val > static_cast<pcl::traits::asType_t<CASE_LABEL>>(val)) -            \
+           (pt_val < static_cast<pcl::traits::asType_t<CASE_LABEL>>(val));             \
+  }
+
+  switch (datatype_)
+  {
+    SAFE_COMPARE(pcl::PCLPointField::BOOL)
```
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/conditional_removal.hpp:538]: true > false should be sufficient, right?

File: io/include/pcl/io/impl/pcd_io.hpp [hunk 5]
```diff
@@ -486,6 +486,13 @@ pcl::PCDWriter::writeASCII (const std::string &file_name, const pcl::PointCloud<
       {
         switch (fields[d].datatype)
         {
+          case pcl::PCLPointField::BOOL:
+          {
+            bool value;
+            memcpy (&value, reinterpret_cast<const char*> (&cloud.points[i]) + fields[d].offset + c * sizeof (bool), sizeof (bool));
+            stream << boost::numeric_cast<std::int32_t>(value);
```
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply io/include/pcl/io/impl/pcd_io.hpp:493]: INT8 are read as chars. Removing other casts can be done in a separate PR

File: tools/transform_point_cloud.cpp (hunk 3 above)
Comment (kunaltyagi) [reply tools/transform_point_cloud.cpp:216]:
```cpp
true * val == val;

false * val == decltype(val){};
```
right?

File: filters/include/pcl/filters/impl/conditional_removal.hpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (mvieth) [reply filters/include/pcl/filters/impl/conditional_removal.hpp:538]: IMO `true` and `false` should not have any greater/less relationship, only equal/not equal. Might be best to create a new subclass to `ComparisonBase`, something like `BoolComparison`? There `compare_val` could be a `bool`.

File: tools/transform_point_cloud.cpp (hunk 3 above)
Comment (mvieth) [reply tools/transform_point_cloud.cpp:216]: Hm, not sure. Why would `x`/`y`/`z` ever be bools? And why would someone scale/transform them? Maybe just make a default case and warn?

File: filters/include/pcl/filters/impl/conditional_removal.hpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/conditional_removal.hpp:538]: Strong ordering is well defined for booleans. I have a feeling I'm missing something here

File: tools/transform_point_cloud.cpp (hunk 3 above)
Comment (kunaltyagi) [reply tools/transform_point_cloud.cpp:221]: Added a warning before the loop. Let the users make a mistake if they so wish 😄

File: io/include/pcl/io/impl/pcd_io.hpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply io/include/pcl/io/impl/pcd_io.hpp:493]: Numeric cast also applies locale. So 100,000 in Germany would be 100.000

File: filters/include/pcl/filters/impl/conditional_removal.hpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/conditional_removal.hpp:538]: PTAL

**Review by koide3 — APPROVED** [review]
LGTM

**Comment by kunaltyagi** [comment]
Resolved conflict

File: common/include/pcl/common/io.h [hunk 6]
```diff
@@ -201,19 +211,25 @@ namespace pcl
   {
     switch (type)
     {
+      case pcl::PCLPointField::BOOL:
+        return 'B';
```
Comment (larshg) [inline common/include/pcl/common/io.h:215]:
```suggestion
        return ('B');
```

Comment (kunaltyagi) [reply common/include/pcl/common/io.h:215]: To keep with others or for some specific reason?

Comment (larshg) [reply common/include/pcl/common/io.h:215]: Similar to the others.

**Comment by larshg** [comment]
I'm a bit with @mvieth about the bool comparison - do we have unit test that covers the new types?

File: io/src/pcd_io.cpp [hunk 7]
```diff
@@ -623,57 +593,27 @@ pcl::PCDReader::readBodyBinary (const unsigned char *map, pcl::PCLPointCloud2 &c
     {
       for (uindex_t c = 0; c < cloud.fields[d].count; ++c)
       {
+#define SET_CLOUD_DENSE(CASE_LABEL)                                                    \
+  case CASE_LABEL: {                                                                   \
+    if (!isValueFinite<pcl::traits::asType_t<CASE_LABEL>>(cloud, i, point_size, d, c)) \
```
Comment (larshg) [inline io/src/pcd_io.cpp:598]: isValueFinite calls std::isFinite but that one doesn't accept bools: https://en.cppreference.com/w/cpp/numeric/math/isfinite - so it will fail?

File: filters/include/pcl/filters/impl/conditional_removal.hpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (mvieth) [reply filters/include/pcl/filters/impl/conditional_removal.hpp:538]: > Strong ordering is well defined for booleans

Could you give a link for that? I didn't really find anything on that topic.
I assume `true>false` is because `1>0`, but just from a logical point of view, it makes no sense that `true` is bigger than `false` - you cannot order them.
And `val` (a `double`) could be `0.0` for `false` and  `1.0` for `true`, but if feel like there are potentially a lot of hidden bugs. Representing a boolean with a double does not make as much sense as representing an actual number with a double.

File: io/src/ascii_io.cpp [hunk 8]
```diff
@@ -249,20 +227,20 @@ pcl::ASCIIReader::typeSize (int type)
 {
   switch (type)
```
Comment (mvieth) [inline io/src/ascii_io.cpp:228]: Use `getFieldSize`?

**Comment by mvieth** [comment]
I think adding tests for the new field types to `test/io/test_io.cpp` would be a good first step.

File: tools/transform_point_cloud.cpp (hunk 3 above)
Comment (kunaltyagi) [reply tools/transform_point_cloud.cpp:234]: Added a conditional warning

File: filters/include/pcl/filters/impl/conditional_removal.hpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/conditional_removal.hpp:538]: https://stackoverflow.com/questions/11951729

I'll take another pass at the logic though

[the remark this answers is not in the document]
Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/conditional_removal.hpp:538]: The main logic of the static_cast is that only non-zero values are true, and they are all true. So,
```cpp
bool a = -0.001;
bool b = 9999.222;

// these are all true
assert(a == b);
assert(a == true);
assert(false < a);
assert(false < b);
```

File: io/src/pcd_io.cpp (hunk 7 above)
Comment (kunaltyagi) [reply io/src/pcd_io.cpp:610]: There's this in your link:
```
4) A set of overloads or a function template accepting the arg argument of any integral type. Equivalent to (2) (the argument is cast to double).
```
This leads to [integral type](https://en.cppreference.com/w/cpp/types/is_integral) which in effect makes it always integral. I'll see if I can modify the `isValueFinite` to skip checking finiteness for integral inputs.

File: common/include/pcl/common/io.h [hunk 9]
```diff
@@ -162,6 +166,8 @@ namespace pcl
     switch (size)
     {
       case 1:
+        if (type == 'B')
```
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply common/include/pcl/common/io.h]: Handled it specially

File: io/src/ascii_io.cpp (hunk 8 above)
Comment (kunaltyagi) [reply io/src/ascii_io.cpp]: Done

File: common/src/pcl_base.cpp [hunk 10]
```diff
@@ -76,6 +76,7 @@ pcl::PCLBase<pcl::PCLPointCloud2>::setInputCloud (const PCLPointCloud2ConstPtr &
   {
     switch (datatype)
     {
+      case pcl::PCLPointField::BOOL:
```
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply common/src/pcl_base.cpp]: Done

**Comment by kunaltyagi** [comment]
@mvieth I want to add a warning that IO for boolean type might result in errors and require manual editing of header to work. What do you think would be the best approach: Documentation or warning on io?

**Review by mvieth — APPROVED** [review]

**Review by larshg — APPROVED** [review]
