### PR TITLE
[surface] Add default initializer to Marching Cubes

### LINKED ISSUE #3717: MarchingCubes is not setting meaningful resolution in default ctor
Default ctor
https://github.com/PointCloudLibrary/pcl/blob/0bb69c0c795e852ddd731039cc1b0ac96b11d8ed/surface/include/pcl/surface/marching_cubes.h#L377-L383

The attributes
https://github.com/PointCloudLibrary/pcl/blob/0bb69c0c795e852ddd731039cc1b0ac96b11d8ed/surface/include/pcl/surface/marching_cubes.h#L436-L442

It won't produce results without proper values e.g.: 32x32x32. First time users then get confused at the absence of output, assuming it doesn't outright segfault.

### PR DESCRIPTION
**Pull request by divmadan**
Fixes #3717

### CODE REVIEW

File: surface/include/pcl/surface/marching_cubes.h [hunk 1]
```diff
@@ -380,6 +380,8 @@ namespace pcl
         percentage_extend_grid_ (percentage_extend_grid),
         iso_level_ (iso_level) 
       {
+        /** \brief Set grid resolution */ 
+        res_x_ = 32; res_y_ = 32; res_z_ = 32;
```
Comment (kunaltyagi) [inline surface/include/pcl/surface/marching_cubes.h]: Is class member default initialization a c++17 feature? We can also use the initializer list here

Comment (taketwo) [reply surface/include/pcl/surface/marching_cubes.h]: No, it's in c++14, so we can use it.

Comment (divmadan) [reply surface/include/pcl/surface/marching_cubes.h]: According to [C.45](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-default), we should use default initializer instead of initializer list, for this case.
Should I proceed in that direction?

Btw, thanks for pointing that out!

Comment (taketwo) [reply surface/include/pcl/surface/marching_cubes.h]: I don't think we have explicitly adopted CppCoreGuidelines, but generally, I see no reason not to follow their suggestions. So yes, please go ahead.

Comment (kunaltyagi) [reply surface/include/pcl/surface/marching_cubes.h]: Please use default initializer since that is already used in several places in PCL for data members.

**Comment by SergioRAgostinho** [comment]
From quickly skimming the code with will generate a 32x32x32 voxel grid. It's not super resolution but the user will be able to see something.
