### PR TITLE
RangeImage: add check before accessing lookup table

### LINKED ISSUE #5143: range_image_border_extraction.cpp (Segmentation fault (core dumped)) Error
Hey all, I have a truble with Segmentation fault.
I use Intel Realsense L515 Lidar.
When I tried GDB for debugging, Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7456303 in pcl::RangeImage::asinLookUp (value=<optimized out>)
     at /home/kjh/pcl/common/include/pcl/range_image/impl/range_image.hpp:58
58 static_cast<float> (lookup_table_size-1) / 2.0f)]);
(gdb)
an error will appear.
There is no problem with the .pcd file, and the same code works when I run the Jetson nano.
When a segment error occurs, it is usually said that it occurs when an unreferenceable memory is accessed, but I have no idea where it went wrong. I tried deleting and reinstalling the pcl library just in case, but to no avail. 
Help me plz....

### PR DESCRIPTION
**Pull request by mvieth**
Fixes #5143
Prevents segfault when `asinLookUp` is called with a NaN value (when there is a (0, 0, 0) point in the input cloud)

### CODE REVIEW

File: common/include/pcl/range_image/impl/range_image.hpp [hunk 1]
```diff
@@ -52,10 +52,14 @@ namespace pcl
...
-      static_cast<int> (
-        static_cast<float> (pcl_lrintf ( (static_cast<float> (lookup_table_size-1) / 2.0f) * value)) + 
-        static_cast<float> (lookup_table_size-1) / 2.0f)]);
+  if (-1.0f<=value && value<=1.0f) { // Also rejects NaN
+    return (asin_lookup_table[
+        static_cast<int> (
+          static_cast<float> (pcl_lrintf ( (static_cast<float> (lookup_table_size-1) / 2.0f) * value)) +
+          static_cast<float> (lookup_table_size-1) / 2.0f)]);
+  } else {
+    return 0.0f;
```
Comment (larshg) [inline common/include/pcl/range_image/impl/range_image.hpp:61]: Should we emit a warning?
Since it seems to happen rarely?

**Review by larshg — APPROVED** [review]
