### PR TITLE
Throw an early exception to prevent divide by zero error (#2481)

### LINKED ISSUE #2481: division by 0
## Your Environment

* PCL Version: the master branch

## Context

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/common.hpp#L80
## Expected Behavior

It should check for 0s before performing divisions.
## Current Behavior

Division by 0 might occur.
## Code to Reproduce

See code above.
## Possible Solution

Check for 0 before doing division.

### PR DESCRIPTION
**Pull request by jatin69**
Closes #2481 

Added a try catch block to throw a length error exception to report that at least 2 elements are required in array to perform the operation.

### CODE REVIEW

File: common/include/pcl/common/impl/common.hpp [hunk 1]
```diff
@@ -70,6 +70,20 @@ pcl::getAngle3D (const Eigen::Vector3f &v1, const Eigen::Vector3f &v2, const boo
 inline void
 pcl::getMeanStd (const std::vector<float> &values, double &mean, double &stddev)
 {
+    try
+    {
+	    // throw a exception when there are less than two elements in vector `values` 
+	    // to prevent division by zero error while calculating standard deviation.
+	    if(values.size() < 2 )
```
Comment (taketwo) [inline common/include/pcl/common/impl/common.hpp]: Why not less than 1?

File: common/include/pcl/common/impl/common.hpp [hunk 2]
```diff
@@ -70,6 +70,20 @@ pcl::getAngle3D (const Eigen::Vector3f &v1, const Eigen::Vector3f &v2, const boo
...
+	    {
+		throw std::length_error("Input array must have atleast 2 elements.");
+	    }
+    } 
+    catch(length_error& e)
```
Comment (taketwo) [inline common/include/pcl/common/impl/common.hpp]: What's the point of throwing an exception and immediately catching it?

File: common/include/pcl/common/impl/common.hpp (hunk 1 above)
Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]: Because standard deviation needs division by `n` and `n-1` as done in this function's last few lines.

File: common/include/pcl/common/impl/common.hpp (hunk 2 above)
Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]: I did not know if any top-level hierarchy is catching any exceptions or not, so I had to catch it here itself. Although I did forget to add a return statement after printing the error message. I'll add it.
But even that leaves the function call in a weird result state. What will the user expect when he passes an empty array? Should I find where this function is called and add a catch block there itself?
Something else on your mind?

Comment (SergioRAgostinho) [reply common/include/pcl/common/impl/common.hpp]: The idea it to let it blow up for the user. That way he'll need to sanitize `values` before passing it to this method.

Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]: oh. If you want to blow up, why throw an exception at all? Aren't exceptions caused to be handled?
Anyway, I'll assume you have a use case in mind for expecting such a behavior.
So, in short,
You want to display a message saying `atleast 2 values` and then crash, yes?

Comment (SergioRAgostinho) [reply common/include/pcl/common/impl/common.hpp]: > oh. If you want to blow up, why throw an exception at all? Aren't exceptions caused to be handled?

Yes but, to be handled by the user ('s code). We have no way of guessing what he wants to do in case he doesn't have a sanitized input. We just want to make sure that he is explicitly dealing with it. 

> You want to display a message saying atleast 2 values and then crash, yes?

Yes.

**Comment by jatin69** [comment]
Hi, sorry it took a long time for such a trivial change. I'm not a frequent contributor.
Please let me know if this needs any more changes.

File: common/include/pcl/common/impl/common.hpp [hunk 3]
```diff
@@ -70,6 +70,14 @@ pcl::getAngle3D (const Eigen::Vector3f &v1, const Eigen::Vector3f &v2, const boo
 inline void
 pcl::getMeanStd (const std::vector<float> &values, double &mean, double &stddev)
 {
+  // throw an exception when there are less than two elements in vector `values` 
+  // to prevent divide by zero error. Then, let the program crash.
+  // Let the user explicity handle this exception as per his needs.
+  if(values.size() < 2 )
+  {
+    throw std::length_error("Input array must have atleast 2 elements.");
```
[the remark this answers is not in the document]
Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]: I'll update this, once you settle on which exception to use.

[the remark this answers is not in the document]
Comment (taketwo) [reply common/include/pcl/common/impl/common.hpp]: Well there is `BadArgumentException` which sort of fits, we may use it. Though I feel there is no consistency within PCL regarding exceptions.

[the remark this answers is not in the document]
Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]:
```cpp
throw pcl::BadArgumentException("Input array must have at least 2 elements.", NULL, "getMeanStd");
```
is this alright?

[the remark this answers is not in the document]
Comment (taketwo) [reply common/include/pcl/common/impl/common.hpp]: I'd use `PCL_THROW_EXCEPTION` following the example here:

https://github.com/PointCloudLibrary/pcl/blob/bf61b8820b27d401ce73a16a5d9952e27a48e72b/common/include/pcl/exceptions.h#L45-L49

[the remark this answers is not in the document]
Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]:
```cpp
PCL_THROW_EXCEPTION(BadArgumentException, "Input array must have at least 2 elements "); 
```
This will do? I thought mentioning the filename will barely make any sense here, as it's just a utility function.

[the remark this answers is not in the document]
Comment (taketwo) [reply common/include/pcl/common/impl/common.hpp]: Yes. But please not my other comment regarding the minimum size of the array.

File: common/include/pcl/common/impl/common.hpp (hunk 1 above)
Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]: Yes. But the code does not handle it. I just tested and `stddev` is `nan` when a single number is passed. I wonder how did that skip testing. I'll update the code to handle it.

File: common/include/pcl/common/impl/common.hpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]: Yes. I commented on that thread. Please see to it.

**Comment by jatin69** [comment]
I handled a missing base case of input size 1 and added an exception for input size 0. Please let me know if is alright and I'll squash commits.

File: common/include/pcl/common/impl/common.hpp [hunk 4]
```diff
@@ -70,6 +70,20 @@ pcl::getAngle3D (const Eigen::Vector3f &v1, const Eigen::Vector3f &v2, const boo
 inline void
 pcl::getMeanStd (const std::vector<float> &values, double &mean, double &stddev)
 {
+  // throw an exception when the input array is empty
+  if(values.size() == 0 )
```
Comment (taketwo) [inline common/include/pcl/common/impl/common.hpp]: Vector has a dedicated function to test whether it is empty. Using it is less verbose and is semantically more clear:

```cpp
if (values.empty ())
```

File: common/include/pcl/common/impl/common.hpp [hunk 5]
```diff
@@ -70,6 +70,20 @@ pcl::getAngle3D (const Eigen::Vector3f &v1, const Eigen::Vector3f &v2, const boo
...
+  {
+    PCL_THROW_EXCEPTION(BadArgumentException, "Error : Input array must have at least 1 element.");
```
Comment (taketwo) [inline common/include/pcl/common/impl/common.hpp]: Please strip the "Error : " prefix, it does not add any information.

File: common/include/pcl/common/impl/common.hpp [hunk 6]
```diff
@@ -70,6 +70,20 @@ pcl::getAngle3D (const Eigen::Vector3f &v1, const Eigen::Vector3f &v2, const boo
...
+  // throw an exception when the input array is empty
+  if(values.size() == 0 )
+  {
+    PCL_THROW_EXCEPTION(BadArgumentException, "Error : Input array must have at least 1 element."); 
+  }
+  
+  // when the array has only one element, mean is the number itself and standard dev is 0
+  if(values.size() == 1)
+  {
+    mean = static_cast<double>(values.at(0));
```
Comment (taketwo) [inline common/include/pcl/common/impl/common.hpp]: There is no reason for an explicit cast here, only makes the line harder to read.

Comment (jatin69) [reply common/include/pcl/common/impl/common.hpp]: @taketwo did the asked changes. Please have a look.

**Comment by jatin69** [comment]
@taketwo Thank you 😄
