### PR TITLE
Fix keep_organized behavior in CropHull filter

### LINKED ISSUE #4854: [filter] Lost behavior with keep_organized flag in CropHull
**Describe the bug**

According specification `pcl::FilterIndices` and all it inheritors must provide opportunity to keep structure of  filtered cloud.
Functions `pcl::FilterIndices::setKeepOrganized()` and `pcl::FilterIndices::setUserFilterValue` must changing default behavior of filter: save size and organization of filtered cloud and fill all outliers by `userFilterValue`.

**Context**

```cpp
pcl::PointCloud<PointT>::Ptr bigStructuredCloud = getCloud();
pcl::CropHull<PointT> filter = getCropHull();
filter.setInpuCloud(bigStructuredCloud);
filter.setKeepOrganized(true);
filter.setUserFilterValue(-10.);
pcl::PointCloud<PointT> filteredBigStructuredCloud;
filter.filter(filteredBigStructuredCloud);
```

**Expected behavior**

```cpp
ASSERT_EQ (bigStructuredCloud->size(), filteredBigStructuredCloud.size());
ASSERT_EQ (bigStructuredCloud->isDense(), filteredBigStructuredCloud.isDense());
```
All outliers was replaced by default value. ( -10. in this case)

**Current Behavior**

`filteredBigStructuredCloud` contains only filtered points. Size is less than original cloud size.

### PR DESCRIPTION
**Pull request by DaniilSNikulin**
part of #3883
resolve #4854

`FilerIndices` , which is Base class of `CropHull` already have got implementation for function `applyFilter(pcl::PointCloud)`.
In Base class keep_organized behavior is exists, but in overridden method in `CropHull` was lost.

`FilterIndices::applyFilter(pcl::PointCloud)`  resolve all needed behavior, so overridden method not needed. 
Because of this, wrong and unnecessary reimplementation was deleted.

Implementation in Base class used protected field `removed_indices_` and expect, that all inheritors will correct fill it.
In `CropHull` this processing does not exists.
In this PR requested processing was implement in ugly temporary way. On the next PR all expected behavior from Base classes will be implement.

### CODE REVIEW

**Comment by kunaltyagi** [comment]
API break added due to removal of:
* `void applyFilter3D (PointCloud &output)`
* `template<unsigned PlaneDim1, unsigned PlaneDim2> void applyFilter2D (PointCloud &output)`

Please correct me if I'm wrong.

**Review by kunaltyagi — DISMISSED** [review]
Not to be merged before 1.12.1 release

**Comment by DaniilSNikulin** [comment]
> API break added due to removal of:
> 
> * `void applyFilter3D (PointCloud &output)`
> * `template<unsigned PlaneDim1, unsigned PlaneDim2> void applyFilter2D (PointCloud &output)`
> 
> Please correct me if I'm wrong.

functions `applyFilter2D` and `applyFilter3D`  are private and not used outside class

**Comment by kunaltyagi** [comment]
You're right. I was betrayed by the diff collapse of github
image

File: test/filters/test_crop_hull.cpp [hunk 1]
```diff
@@ -356,6 +356,31 @@ TYPED_TEST (PCLCropHullTestFixture, test_cloud_filtering)
...
+    crop_hull_filter.setKeepOrganized(true);
+    crop_hull_filter.setUserFilterValue(-10.);
+    const pcl::PointXYZ defaultPoint(-10., -10., -10.);
+    for (TestData const & test_data : entry.second)
+    {
+      crop_hull_filter.setInputCloud(test_data.input_cloud_);
+      pcl::PointCloud<pcl::PointXYZ> filteredCloud;
+      crop_hull_filter.filter(filteredCloud);
+      ASSERT_EQ (test_data.input_cloud_->size(), filteredCloud.size());
+      for (pcl::index_t i = 0; i < pcl::index_t(test_data.input_cloud_->size()); ++i)
```
Comment (kunaltyagi) [inline test/filters/test_crop_hull.cpp:374]: If test_data.input_cloud_ isn't an index, then don't use index_t for i, and just use size_t.

Comment (DaniilSNikulin) [reply test/filters/test_crop_hull.cpp]: applied the suggestion

**Comment by DaniilSNikulin** [comment]
If `CropHull`  will contain function `applyFilter(PointCLoud)` with trivial implementation (call Base class method) ABI backward compatibility will be saved.
Should I keep the overridden function to avoid ABI break?

**Comment by kunaltyagi** [comment]
Yes, that would be nice. We can have that function removed via another PR targeted at 1.13

**Comment by DaniilSNikulin** [comment]
restored ABI backward compatibility

File: filters/include/pcl/filters/impl/crop_hull.hpp [hunk 2]
```diff
@@ -40,37 +40,24 @@
...
-    else if (range[1] <= range[2] && range[1] <= range[0])
-      applyFilter2D<2,0> (output);
-    else
-      applyFilter2D<0,1> (output);
-  }
-  else
-  {
-    applyFilter3D (output);
-  }
+  //TODO: remove overriden function with trivial reimplementation
```
Comment (kunaltyagi) [inline filters/include/pcl/filters/impl/crop_hull.hpp:48]: https://godbolt.org/z/vsKcWKMeP

**Review by kunaltyagi — CHANGES_REQUESTED** [review]

File: filters/include/pcl/filters/impl/crop_hull.hpp (hunk 2 above)
Comment (DaniilSNikulin) [reply filters/include/pcl/filters/impl/crop_hull.hpp:48]: Do I understand correctly? Are you want some like this:
```cpp
PCL_DEPRECATED(1, 12, "This method is trivially call Base and must be removed")
```

File: filters/include/pcl/filters/crop_hull.h [hunk 3]
```diff
@@ -177,17 +169,6 @@ namespace pcl
...
          */
       void
-      applyFilter3D (PointCloud &output);
-
-      /** \brief Apply the three-dimensional hull filter.
-        *  Polygon-ray crossings are used for three rays cast from each point
-        *  being tested, and a  majority vote of the resulting
-        *  polygon-crossings is used to decide  whether the point lies inside
-        *  or outside the hull.
-        * \param[out] indices The indices of the set of points that pass the 3D
```
Comment (mvieth) [inline filters/include/pcl/filters/crop_hull.h:187]: You are deleting the wrong documentation here

File: filters/include/pcl/filters/impl/crop_hull.hpp [hunk 4]
```diff
@@ -135,46 +122,21 @@ pcl::CropHull<PointT>::applyFilter2D (PointCloud &output)
          ))
       {
         if (crop_outside_)
-          output.push_back ((*input_)[(*indices_)[index]]);
-        // once a point has tested +ve for being inside one polygon, we can
```
Comment (mvieth) [inline filters/include/pcl/filters/impl/crop_hull.hpp:139]: Would be great if you could save these other comments as well

File: filters/include/pcl/filters/crop_hull.h (hunk 3 above)
Comment (DaniilSNikulin) [reply filters/include/pcl/filters/crop_hull.h]: It is my fault. I was careless.
Thanks you for finding this mistake.

File: filters/include/pcl/filters/impl/crop_hull.hpp (hunk 4 above)
Comment (DaniilSNikulin) [reply filters/include/pcl/filters/impl/crop_hull.hpp:139]: returned back lost comments

File: filters/include/pcl/filters/impl/crop_hull.hpp (hunk 2 above)
Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/crop_hull.hpp:48]: Yeah. Something like: "This is a trivial call to base class method" The removal message is auto-added by the macro

Comment (DaniilSNikulin) [reply filters/include/pcl/filters/impl/crop_hull.hpp]: done

Comment (DaniilSNikulin) [reply filters/include/pcl/filters/impl/crop_hull.hpp]: but I have some problem with message warnings:
1. if current version less than deprecated target, warning are not exists
1. else:
```
/home/ros/tmp/pcl/common/include/pcl/pcl_macros.h:162:11: error: 'unneeded_deprecation' does not name a type
           unneeded_deprecation),                                                       \
           ^
/home/ros/tmp/pcl/common/include/pcl/pcl_macros.h:157:3: note: in expansion of macro '_PCL_COMPAT_MAJOR_VERSION'
   _PCL_COMPAT_MAJOR_VERSION(                                                           \
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ros/tmp/pcl/common/include/pcl/pcl_macros.h:159:7: note: in expansion of macro '_PCL_COMPAT_MINOR_VERSION'
       _PCL_COMPAT_MINOR_VERSION(                                                       \
       ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ros/tmp/pcl/filters/include/pcl/filters/impl/crop_hull.hpp:46:1: note: in expansion of macro 'PCL_DEPRECATED'
 PCL_DEPRECATED(1, 12, "This is a trivial call to base class method")
 ```
 
 I have tested also with already exists macros and behavior are same:
 ```
 /home/ros/tmp/pcl/common/include/pcl/pcl_macros.h:162:11: error: 'unneeded_deprecation' does not name a type
           unneeded_deprecation),                                                       \
           ^
/home/ros/tmp/pcl/common/include/pcl/pcl_macros.h:157:3: note: in expansion of macro '_PCL_COMPAT_MAJOR_VERSION'
   _PCL_COMPAT_MAJOR_VERSION(                                                           \
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ros/tmp/pcl/common/include/pcl/pcl_macros.h:159:7: note: in expansion of macro '_PCL_COMPAT_MINOR_VERSION'
       _PCL_COMPAT_MINOR_VERSION(                                                       \
       ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ros/tmp/pcl/filters/include/pcl/filters/passthrough.h:154:7: note: in expansion of macro 'PCL_DEPRECATED'
       PCL_DEPRECATED(1, 12, "use inherited FilterIndices::setNegative() instead")
```

**Review by kunaltyagi — APPROVED** [review]

File: filters/include/pcl/filters/impl/crop_hull.hpp [hunk 5]
```diff
@@ -40,37 +40,25 @@
 
 #include <pcl/filters/crop_hull.h>
 
+
 //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-template<typename PointT> void
+template<typename PointT>
+PCL_DEPRECATED(1, 13, "This is a trivial call to base class method")
```
Comment (kunaltyagi) [inline filters/include/pcl/filters/impl/crop_hull.hpp:46]:
```suggestion
PCL_DEPRECATED(1, 16, "This is a trivial call to base class method")
```

**Review by kunaltyagi — DISMISSED** [review]

File: filters/include/pcl/filters/impl/crop_hull.hpp (hunk 2 above)
Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/crop_hull.hpp]: Yes. The version in the deprecated macro are when this needs to be removed.

File: filters/include/pcl/filters/impl/crop_hull.hpp [hunk 6]
```diff
@@ -40,37 +40,25 @@
 
 #include <pcl/filters/crop_hull.h>
 
+
 //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-template<typename PointT> void
+template<typename PointT>
+PCL_DEPRECATED(1, 16, "This is a trivial call to base class method")
```
Comment (mvieth) [inline filters/include/pcl/filters/impl/crop_hull.hpp:46]: @kunaltyagi Wasn't 1.13 correct? This is supposed to be a reminder that we remove this function just before releasing 1.13.0, right? Not a usual deprecation because the `applyFilter` from the `FilterIndices` will seamlessly replace this?

Comment (kunaltyagi) [reply filters/include/pcl/filters/impl/crop_hull.hpp:46]: 🤦🏾 Yeah.
```suggestion
PCL_DEPRECATED(1, 13, "This is a trivial call to base class method")
```

**Review by mvieth — APPROVED** [review]

**Review by kunaltyagi — APPROVED** [review]

**Comment by haoyuefan** [comment]
Hi,

How can I use this change in the 1.7 release? I installed the PCL library via apt-get, but the setKeepOrganized CropHull filter doesn't work. I want to re-implement the CropHull filter in my code to make setKeepOrganized work. What should I do?

Thank You.

@kunaltyagi @DaniilSNikulin

**Comment by mvieth** [comment]
@haoyuefan You could probably copy the current versions of crop_hull.h and crop_hull.hpp to your own project, and get it to work after some renaming. But I would recommend that you instead compile the current master branch and use that instead of the version from apt-get if you need the newest features and improvements.

**Comment by kunaltyagi** [comment]
Manually adding this patch and rebuilding (and removing the apt installed version)
