### PR TITLE
Fix regression in Organized Edge Detection (introduced in PCL 1.10.1)

### LINKED ISSUE #4274: [features] Code Simplification introduced logic bug in OrganizedEdgeDetection
** Summary **

A code change in commit 8092d6529eed0b489f3c7ab50be018f20b6da2bb subtly changed the logic in the extractEdges method of OrganizedEdgeDetection and causes occluded and occluding edges to be categorized incorrectly.

**Expected behavior**

Occluding and occluded edge extraction to perform the same as previous versions of PCL before 1.10.1

**Current Behavior**

Occluding and occluded edges are clearly miscategorized.  Although the total number of indices between the two matches previous versions of PCL, the edges types are incorrectly determined due to a logic bug.

**To Reproduce**

Run PCL 1.10.1 or later

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 20.04]
 - Compiler: [GCC 9.3.0]
 - PCL Version [1.11]

**Possible Solution**

Line 135 of organized_edge_detection.hpp in commit 8092d6529eed0b489f3c7ab50be018f20b6da2bb should be reverted.

### PR DESCRIPTION
**Pull request by kunaltyagi**
Supersedes and closes #4275

closes #4274

### CODE REVIEW

File: test/features/test_organized_edge_detection.cpp [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+#include <pcl/point_types.h>
+
+namespace {
+class OrganizedPlaneDetectionTestFixture : public ::testing::Test {
+protected:
+  const int INNER_SQUARE_EDGE_LENGTH = 50;
+  const int OUTER_SQUARE_EDGE_LENGTH = INNER_SQUARE_EDGE_LENGTH * 2;
+  const float SYNTHETIC_CLOUD_BASE_DEPTH = 2.0;
+  const float SYNTHETIC_CLOUD_DEPTH_DISCONTINUITY = .02f;
+  const float SYNTHETIC_CLOUD_RESOLUTION = 0.01f;
```
Comment (SergioRAgostinho) [inline test/features/test_organized_edge_detection.cpp:22]: contexpr all things

File: test/features/test_organized_edge_detection.cpp [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+    // discontinuity between neighboring pixels.  The base depth and resolution are
+    // arbitrary and useful for visualizing the cloud.  The discontinuity of the
+    // generated cloud must be greater than the threshold set when running the
+    // organized edge detection algorithm.
+    const auto outer_square_ctr = OUTER_SQUARE_EDGE_LENGTH / 2;
+    const auto inner_square_ctr = INNER_SQUARE_EDGE_LENGTH / 2;
+    const auto left_col = outer_square_ctr - inner_square_ctr;
+    const auto right_col = outer_square_ctr + inner_square_ctr;
+    const auto top_row = outer_square_ctr - inner_square_ctr;
+    const auto bottom_row = outer_square_ctr + inner_square_ctr;
```
Comment (SergioRAgostinho) [inline test/features/test_organized_edge_detection.cpp:52]: constexpr all things

File: test/features/test_organized_edge_detection.cpp [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+
+    for (auto row = 0; row < OUTER_SQUARE_EDGE_LENGTH; ++row) {
+      for (auto col = 0; col < OUTER_SQUARE_EDGE_LENGTH; ++col) {
+        float x = col - outer_square_ctr;
+        float y = row - inner_square_ctr;
```
Comment (SergioRAgostinho) [inline test/features/test_organized_edge_detection.cpp:57]: const

File: test/features/test_organized_edge_detection.cpp [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+  const auto MAX_SEARCH_NEIGHBORS = 8;
+
+  // The depth discontinuity check to determine whether an edge exists is linearly
+  // dependent on the depth of the points in the cloud (not a fixed distance).  The
+  // algorithm iterates through each point in the cloud and finding the neighboring
+  // point with largest discontinuity value.  That value is compared against a threshold
+  // multiplied by the actual depth value of the point. Therefore:
+  // abs(SYNTHETIC_CLOUD_DEPTH_DISCONTINUITY) must be greater than
+  // DEPTH_DISCONTINUITY_THRESHOLD * abs(SYNTHETIC_CLOUD_BASE_DEPTH)
+  const auto DEPTH_DISCONTINUITY_THRESHOLD =
```
Comment (SergioRAgostinho) [inline test/features/test_organized_edge_detection.cpp:118]: constexpr

File: test/features/test_organized_edge_detection.cpp [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+  auto labels = pcl::PointCloud<pcl::Label>();
+  auto label_indices = std::vector<pcl::PointIndices>();
+
+  oed.setEdgeType(oed.EDGELABEL_OCCLUDING | oed.EDGELABEL_OCCLUDED);
+  oed.setInputCloud(cloud_);
+  oed.setDepthDisconThreshold(DEPTH_DISCONTINUITY_THRESHOLD);
+  oed.setMaxSearchNeighbors(MAX_SEARCH_NEIGHBORS);
+  oed.compute(labels, label_indices);
+
+  auto occluding_indices =
```
Comment (SergioRAgostinho) [inline test/features/test_organized_edge_detection.cpp:131]: const

File: test/features/test_organized_edge_detection.cpp [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+      std::set<index_t>(label_indices[1].indices.begin(), label_indices[1].indices.end());
+  EXPECT_EQ(occluding_indices, outer_perimeter_);
+
+  auto occluded_indices =
```
Comment (SergioRAgostinho) [inline test/features/test_organized_edge_detection.cpp:135]: const
