### PR TITLE
Fix missing symbol issue on Windows for `filters::convolution` and `poisson4::bspline`

### LINKED ISSUE #4082: [windows] symbol not found: `filters::Convolution<RGB,RGB>::convolveOne{Row,Col}Dense()`
**Describe the bug**

pcl_linemod_detection and pcl_train_linemod_template are failed build on Windows.  

```
------ ビルド開始: プロジェクト: pcl_linemod_detection, 構成: Release x64 ------
Building Custom Rule C:/pcl-1.11.0/tools/CMakeLists.txt
linemod_detection.cpp
C:\pcl-1.11.0\tools\linemod_detection.cpp(117,1): warning C4996: 'pcl::PointCloud<pcl::PointXYZRGBA>::mapping_': rewrite your code to avoid using this protected field (It will be removed in PCL 1.12)
linemod_detection.obj : error LNK2001: 外部シンボル ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColDense(int,int)" (?convolveOneColDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" は未解決です。
linemod_detection.obj : error LNK2001: 外部シンボル ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowDense(int,int)" (?convolveOneRowDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" は未解決です。
C:\pcl-1.11.0\build\bin\pcl_linemod_detection.exe : fatal error LNK1120: 2 件の未解決の外部参照
プロジェクト "pcl_linemod_detection.vcxproj" のビルドが終了しました -- 失敗。
```
```
------ ビルド開始: プロジェクト: pcl_train_linemod_template, 構成: Release x64 ------
Building Custom Rule C:/pcl-1.11.0/tools/CMakeLists.txt
train_linemod_template.cpp
C:\pcl-1.11.0\tools\train_linemod_template.cpp(227,1): warning C4996: 'pcl::PointCloud<pcl::PointXYZRGBA>::mapping_': rewrite your code to avoid using this protected field (It will be removed in PCL 1.12)
train_linemod_template.obj : error LNK2001: 外部シンボル ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColDense(int,int)" (?convolveOneColDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" は未解決です。
train_linemod_template.obj : error LNK2001: 外部シンボル ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowDense(int,int)" (?convolveOneRowDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" は未解決です。
C:\pcl-1.11.0\build\bin\pcl_train_linemod_template.exe : fatal error LNK1120: 2 件の未解決の外部参照
プロジェクト "pcl_train_linemod_template.vcxproj" のビルドが終了しました -- 失敗。
```

**To Reproduce**
Build PCL with enable BUILD_tools on Windows.

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: Visual Studio 2019 (x64)
 - PCL Version: PCL 1.11.0

### PR DESCRIPTION
**Pull request by OgreTransporter**
Here is a new bugfix for problem #4082. This is a different approach than in PR #4151. Instead of undoing PRs #3972 and #3971, we use PCL_EXPORTS here. Many thanks to larshg who found the solution.

Closes #4082

### CODE REVIEW

**Comment by OgreTransporter** [comment]
@UnaNancyOwen, @SunBlack: Could you please also test this solution in your environments?

**Comment by SunBlack** [comment]
Looks good 👍 
image

File: filters/include/pcl/filters/convolution.h [hunk 1]
```diff
@@ -72,7 +72,7 @@ namespace pcl
       */
 
     template <typename PointIn, typename PointOut>
-    class Convolution
+    class PCL_EXPORTS Convolution
```
Comment (kunaltyagi) [inline filters/include/pcl/filters/convolution.h:75]: Can we use this instead on the functions directly? (Like what you did for `BSplineElements`)

File: test/filters/test_convolution.cpp [hunk 2]
```diff
@@ -41,43 +41,59 @@
...
-PointCloud<PointXYZI>::Ptr input (new PointCloud<PointXYZI> ());
-Eigen::ArrayXf filter(7);
+typedef struct
+{
+  float r;
+  float g;
+  float b;
+} COLOR;
+
+static const COLOR basemap[6] = {
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:56]: Why not using `std::array`?

File: test/filters/test_convolution.cpp [hunk 3]
```diff
@@ -41,43 +41,59 @@
...
+  { 0.2902f, 0.0784f, 0.5490f },
+  { 0.1176f, 0.5333f, 0.8980f },
+  { 0.5451f, 0.7647f, 0.2902f },
+  { 1.0000f, 0.9216f, 0.2314f },
+  { 1.0000f, 0.0000f, 0.0000f },
+};
+
+COLOR get_color(COLOR* colormap, size_t color_count, float fmin, float fmax, float value)
+{
+  float* steps = new float[color_count];
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:66]: Why not using `std::array`?

File: test/filters/test_convolution.cpp [hunk 4]
```diff
@@ -41,43 +41,59 @@
...
+  float f = (fmax - fmin) / (float)(color_count - 1);
+  for (int i = 0; i < (int)color_count; i++)
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:68]: Why downcast to `int`?

File: test/filters/test_convolution.cpp [hunk 5]
```diff
@@ -41,43 +41,59 @@
...
+    steps[i] = fmin + f * (float)i;
+  COLOR result = { 0, 0, 0 };
+  if (value < fmin) value = fmin;
+  if (value > fmax) value = fmax;
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:72]: Maybe use `value = std:min(fmax, std::max(value, fmin))` instead (`std::clamp` is C++17 :-( )

File: test/filters/test_convolution.cpp [hunk 6]
```diff
@@ -41,43 +41,59 @@
...
+  for (size_t i = 1; i < color_count; i++)
+  {
+    if (steps[i - 1] <= value && value <= steps[i])
+    {
+      result.r = (colormap[i - 1].r == colormap[i].r) ? colormap[i].r : (colormap[i - 1].r + ((colormap[i].r - colormap[i - 1].r) / (steps[i] - steps[i - 1])) * (value - steps[i - 1]));
+      result.g = (colormap[i - 1].g == colormap[i].g) ? colormap[i].g : (colormap[i - 1].g + ((colormap[i].g - colormap[i - 1].g) / (steps[i] - steps[i - 1])) * (value - steps[i - 1]));
+      result.b = (colormap[i - 1].b == colormap[i].b) ? colormap[i].b : (colormap[i - 1].b + ((colormap[i].b - colormap[i - 1].b) / (steps[i] - steps[i - 1])) * (value - steps[i - 1]));
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:79]: Has `colormap` an iterator, so you could write
```
for (std::size_t c = 0; c < 3; ++c) {
  result.r = (colormap[i - 1][c] == colormap[i][c]) ? colormap[i][c] : (colormap[i - 1][c] + ((colormap[i][c] - colormap[i - 1][c]) / (steps[i] - steps[i - 1])) * (value - steps[i - 1]));
}
```

File: test/filters/test_convolution.cpp [hunk 7]
```diff
@@ -3155,6 +3171,151 @@ main (int argc, char** argv)
...
... output_47[15] = 114.35; output_47[16] = 113.588; output_47[17] = 112.99; output_47[18] = 111.645; output_47[19] = 110.009; output_47[20] = 109.13; output_47[21] = 108.771; output_47[22] = 108.592; output_47[23] = 108.641; output_47[24] = 108.345; output_47[25] = 107.592; output_47[26] = 107.063; output_47[27] = 106.767; output_47[28] = 106.592; output_47[29] = 106.645; output_47[30] = 106.399; output_47[31] = 105.843; output_47[32] = 105.57; output_47[33] = 105.502; output_47[34] = 105.557; output_47[35] = 105.672; output_47[36] = 105.56; output_47[37] = 104.897; output_47[38] = 104.642; output_47[39] = 104.708; output_47[40] = 104.054; output_47[41] = 103.556; output_47[42] = 103.982; output_47[43] = 104.43; output_47[44] = 104.682; output_47[45] = 104.596; output_47[46] = 104.104; output_47[47] = 103.852; output_47[48] = 103.964; output_47[49] = 103.91; output_47[50] = 103.556; output_47[51] = 102.614; output_47[52] = 102.126; output_47[53] = 102.762; output_47[54] = 103.466; output_47[55] = 103.273; output_47[56] = 102.292; output_47[57] = 101.363; output_47[58] = 100.821; output_47[59] = 100.538; output_47[60] = 100.332; output_47[61] = 0; output_47[62] = 0; output_47[63] = 0;
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:3187]: Please on separate lines.

File: test/filters/test_convolution.cpp [hunk 8]
```diff
@@ -3155,6 +3171,151 @@ main (int argc, char** argv)
...
+
+  std::uint32_t j = 0;
+  for (std::uint32_t i = 0; i < output->width ; ++i)
+    EXPECT_NEAR ((*output) (i,j).intensity, output_0[i], 1e-3);
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:3191]: Why not `EXPECT_FLOAT_EQ` or `EXPECT_DOUBLE_EQ`?

File: test/filters/test_convolution.cpp [hunk 9]
```diff
@@ -3155,6 +3171,151 @@ main (int argc, char** argv)
...
+  using namespace pcl::common;
+  using namespace pcl::filters;
+
+  PointCloud<RGB>::Ptr input (new PointCloud<RGB> ());
+  Eigen::ArrayXf filter(7);
+  pcl::filters::Convolution<RGB, RGB> convolve;
+  PointCloud<RGB>::Ptr output;
+
+  // input
+  filter << 0.00443305, 0.0540056, 0.242036, 0.39905, 0.242036, 0.0540056, 0.00443305;
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:3209]: Define `Eigen::ArrayXf filter(7);` in leine before, so it is easier to see that these are the initiale values.

File: test/filters/test_convolution.cpp [hunk 10]
```diff
@@ -3155,6 +3171,151 @@ main (int argc, char** argv)
...
+  convolve.setKernel (filter);
+  convolve.convolveRows (*output);
+
+  // first output row
+  std::uint32_t i = 0;
+  for (std::uint32_t j = 0; j < output->width; ++j)
+  {
+    EXPECT_NEAR((*output) (i, j).r, 0, 1e-3);
+    EXPECT_NEAR((*output) (i, j).g, 0, 1e-3);
+    EXPECT_NEAR((*output) (i, j).b, 0, 1e-3);
```
Comment (SunBlack) [inline test/filters/test_convolution.cpp:3239]: Same as above

File: filters/include/pcl/filters/convolution.h (hunk 1 above)
Comment (OgreTransporter) [reply filters/include/pcl/filters/convolution.h:75]: I wanted to do all the functions at once. That had the advantage that if you want to move more functions you don't have to think about it anymore. Now I have changed that. When moving functions you have to pay attention to PCL_EXPORTS yourself.

File: test/filters/test_convolution.cpp (hunk 3 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:66]: I've changed that, too.

Comment (SunBlack) [reply test/filters/test_convolution.cpp:66]: Sorry `std::vector`as it is dynamic.

File: test/filters/test_convolution.cpp (hunk 4 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:68]: To disable the warning to compare signed and unsigned. I changed the loop to size_t.

File: test/filters/test_convolution.cpp (hunk 5 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:72]: I've changed that, too.

File: test/filters/test_convolution.cpp (hunk 7 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:3187]: I changed the original test as little as possible. But I can add line breaks.

https://github.com/PointCloudLibrary/pcl/blob/0b63c9e8dd63e640998ab587ae9c642eccf3b2c9/test/filters/test_convolution.cpp#L68

File: test/filters/test_convolution.cpp (hunk 8 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:3191]: I have no idea. I didn't build that test. I just quickly copied my test from it. But when I use EXPECT_FLOAT_EQ the test fails.

File: test/filters/test_convolution.cpp (hunk 9 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:3209]: Ok

File: test/filters/test_convolution.cpp (hunk 10 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:3239]: In my tests I can use EXPECT_FLOAT_EQ I have changed that.

File: test/filters/test_convolution.cpp (hunk 3 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp]: I changed the function. Now the fixed color scale is used.

File: test/filters/test_convolution.cpp [hunk 11]
```diff
@@ -41,44 +41,50 @@
...
+  float f = (fmax - fmin) / (float)(colormap.size() - 1);
+  for (size_t i = 0; i < colormap.size(); i++)
+    steps[i] = fmin + f * (float)i;
+  value = std::min<float>(fmax, std::max<float>(value, fmin));
+  RGB result;
+  for (size_t i = 1; i < colormap.size(); i++)
+  {
+    if (steps[i - 1] <= value && value <= steps[i])
+    {
+      result.r = (colormap[i - 1].r == colormap[i].r) ? colormap[i].r : (uint8_t)((float)colormap[i - 1].r + (((float)colormap[i].r - (float)colormap[i - 1].r) / (steps[i] - steps[i - 1])) * (value - steps[i - 1]));
```
Comment (kunaltyagi) [inline test/filters/test_convolution.cpp:73]: Use a lambda to take lower, upper and t (0 to 1) to interpolate the value.

File: test/filters/test_convolution.cpp [hunk 12]
```diff
@@ -41,44 +41,50 @@
...
-
-  std::uint32_t j = 0;
-  for (std::uint32_t i = 0; i < output->width ; ++i)
-    EXPECT_NEAR ((*output) (i,j).intensity, output_0[i], 1e-3);
-  j = 47;
-  for (std::uint32_t i = 0; i < output->width ; ++i)
-    EXPECT_NEAR ((*output) (i,j).intensity, output_47[i], 1e-3);
+  std::array<float, 5> steps;
+  float f = (fmax - fmin) / (float)(colormap.size() - 1);
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:64]: ???

File: test/filters/test_convolution.cpp [hunk 13]
```diff
@@ -41,44 +41,50 @@
...
+std::array<RGB, 5> colormap {
+  RGB(74, 19, 139),
+  RGB(29, 135, 228),
+  RGB(139, 194, 74),
+  RGB(255, 235, 59),
+  RGB(255, 0, 0),
+};
 
-TEST (Convolution, convolveRows)
+RGB get_color(float fmin, float fmax, float value)
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:61]: The mathematical functions generate a 3D image. Depending on Z, the color is taken from a color set. The function `get_color` looks for the matching interval from the color set and interpolates the value.

File: test/filters/test_convolution.cpp [hunk 14]
```diff
@@ -41,44 +41,50 @@
...
-    EXPECT_NEAR ((*output) (i,j).intensity, output_47[i], 1e-3);
+  std::array<float, 5> steps;
+  float f = (fmax - fmin) / (float)(colormap.size() - 1);
+  for (size_t i = 0; i < colormap.size(); i++)
+    steps[i] = fmin + f * (float)i;
+  value = std::min<float>(fmax, std::max<float>(value, fmin));
+  RGB result;
+  for (size_t i = 1; i < colormap.size(); i++)
+  {
+    if (steps[i - 1] <= value && value <= steps[i])
```
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply test/filters/test_convolution.cpp:71]: I made a typo. The numerator is the distance from lower bound. So, here, it'd be (1.5 - (-1.6)) = 3.1

The final value would be int(3.1/0.8) = 3

File: test/filters/test_convolution.cpp (hunk 13 above)
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply test/filters/test_convolution.cpp:61]: `interpolate_color` would be a better name in that case.

File: test/filters/test_convolution.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply test/filters/test_convolution.cpp:64]: Sorry. Substitute f with more verbose step_size in this function

File: test/filters/test_convolution.cpp [hunk 15]
```diff
@@ -41,44 +41,50 @@
...
+  }
+  return result;
 }
 
-int
-main (int argc, char** argv)
+TEST (Convolution, convolveRowsXYZI)
 {
+  // input
+  Eigen::ArrayXf filter(7);
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:85]: The `setKernel` function of `Convolution` only accepts `Eigen::ArrayXf`

File: test/filters/test_convolution.cpp (hunk 6 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp]: `RGB` has no index operator

File: test/filters/test_convolution.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:71]: This makes more sense ;-)
I changed the function.

File: test/filters/test_convolution.cpp (hunk 11 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp]: I use a lambda function for interpolation.

**Comment by OgreTransporter** [comment]
I have built and run the test as debug and release with Visual Studio 2017 and 2019 on different computers. Works fine for me.

File: test/filters/test_convolution.cpp [hunk 16]
```diff
@@ -3155,6 +3158,268 @@ main (int argc, char** argv)
...
+
+  // filter
+  PointCloud<PointXYZRGB>::Ptr output;
+  output.reset (new PointCloud<PointXYZRGB> ());
+  pcl::filters::Convolution<PointXYZRGB, PointXYZRGB> convolve;
+  convolve.setInputCloud (input);
+  convolve.setKernel (filter);
+  convolve.convolveRows (*output);
+
+  // first output row
```
Comment (kunaltyagi) [inline test/filters/test_convolution.cpp:3395]: Please add a note that this is because of border policy ignore which sets the border of width = filter_size/2 as NaN for xyz and 0 for rgb values.

File: test/filters/test_convolution.cpp [hunk 17]
```diff
@@ -58,25 +59,21 @@ std::array<RGB, 5> colormap {
   RGB(255, 0, 0),
 };
 
-RGB get_color(float fmin, float fmax, float value)
+RGB interpolate_color(float fmin, float fmax, float value)
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:62]: `auto interpolate = [](uint8_t color0, uint8_t color1, float step_size, float value) {`
Is this ok for you?

File: test/filters/test_convolution.cpp [hunk 18]
```diff
@@ -58,25 +59,21 @@ std::array<RGB, 5> colormap {
...
-      break;
-    }
-  }
-  return result;
+  if (value <= fmin) return colormap[0];
+  if (value >= fmax) return colormap[colormap.size() - 1];
+  float step_size = (fmax - fmin) / (float)(colormap.size() - 1);
+  size_t low_index = static_cast<size_t>((value - fmin) / step_size);
+  if(value == fmin + (float)low_index * step_size) return colormap[low_index];
+  auto interpolate_channel = [](uint8_t c0, uint8_t c1, float f, float value, float offset) {
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:69]: See above

File: test/filters/test_convolution.cpp [hunk 19]
```diff
@@ -58,25 +59,21 @@ std::array<RGB, 5> colormap {
...
-      result.r = (colormap[i - 1].r == colormap[i].r) ? colormap[i].r : (uint8_t)((float)colormap[i - 1].r + (((float)colormap[i].r - (float)colormap[i - 1].r) / (steps[i] - steps[i - 1])) * (value - steps[i - 1]));
-      result.g = (colormap[i - 1].g == colormap[i].g) ? colormap[i].g : (uint8_t)((float)colormap[i - 1].g + (((float)colormap[i].g - (float)colormap[i - 1].g) / (steps[i] - steps[i - 1])) * (value - steps[i - 1]));
-      result.b = (colormap[i - 1].b == colormap[i].b) ? colormap[i].b : (uint8_t)((float)colormap[i - 1].b + (((float)colormap[i].b - (float)colormap[i - 1].b) / (steps[i] - steps[i - 1])) * (value - steps[i - 1]));
-      break;
-    }
-  }
-  return result;
+  if (value <= fmin) return colormap[0];
+  if (value >= fmax) return colormap[colormap.size() - 1];
+  float step_size = (fmax - fmin) / (float)(colormap.size() - 1);
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:66]: Ok

File: test/filters/test_convolution.cpp (hunk 18 above)
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:69]: Before calling the function I subtract the offset from the value. Of course this works too.

File: test/filters/test_convolution.cpp [hunk 20]
```diff
@@ -58,25 +59,21 @@ std::array<RGB, 5> colormap {
...
+  size_t low_index = static_cast<size_t>((value - fmin) / step_size);
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:67]: Ok

File: test/filters/test_convolution.cpp (hunk 16 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:3395]: Ok

File: test/filters/test_convolution.cpp (hunk 17 above)
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply test/filters/test_convolution.cpp:62]: `auto interpolate = [](uint8_t lower, uint8_t upper, float value)`

File: test/filters/test_convolution.cpp [hunk 21]
```diff
@@ -3155,6 +3158,268 @@ main (int argc, char** argv)
   (*input) (61,47).intensity = 100;
   (*input) (62,47).intensity = 98;
   (*input) (63,47).intensity = 96;
+
+  // filter
+  PointCloud<PointXYZI>::Ptr output;
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:3163]: From SunBlack:
> Define Eigen::ArrayXf filter(7); inline before, so it is easier to see that these are the initiale values.

So I defined all variables near the initialization, which is not a bad idea because there is so much data in the first test.

File: test/filters/test_convolution.cpp [hunk 22]
```diff
@@ -44,6 +44,7 @@
 #include <cmath>
 #include <array>
 #include <algorithm>
+#include <functional>
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:47]: Ok

File: test/filters/test_convolution.cpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (kunaltyagi) [reply test/filters/test_convolution.cpp:3163]: How is this related to my comment?

**Comment by UnaNancyOwen** [comment]
LGTM 👍

File: test/filters/test_convolution.cpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:3163]: I got that wrong. I would still do without it because I know that the double bracket `>>' at the end of `auto {in,out}put = pcl::make_shared<PointCloud<PointXYZI>>();` can cause problems with some compiler versions. Yes, you can prevent this by putting a space in between. But I don't find this solution very robust, because some IDEs can delete them during automatic code formatting.

[the remark this answers is not in the document]
Comment (kunaltyagi) [reply test/filters/test_convolution.cpp]: > can cause problems with some compiler versions

That was true for old compilers (pre C++11). Since we support only C++14 (or newer), it's not a concern for a conformant compiler

File: test/filters/test_convolution.cpp [hunk 23]
```diff
@@ -41,44 +41,47 @@
...
-
-  std::uint32_t j = 0;
-  for (std::uint32_t i = 0; i < output->width ; ++i)
-    EXPECT_NEAR ((*output) (i,j).intensity, output_0[i], 1e-3);
-  j = 47;
-  for (std::uint32_t i = 0; i < output->width ; ++i)
-    EXPECT_NEAR ((*output) (i,j).intensity, output_47[i], 1e-3);
+  if (value <= lower_bound) return colormap[0];
+  if (value >= upper_bound) return colormap[colormap.size() - 1];
```
Comment (kunaltyagi) [inline test/filters/test_convolution.cpp:64]: `colormap.back()` is shorter

File: test/filters/test_convolution.cpp [hunk 24]
```diff
@@ -41,44 +41,47 @@
...
+  float step_size = (upper_bound - lower_bound) / static_cast<float>(colormap.size() - 1);
+  std::size_t lower_index = static_cast<std::size_t>((value - lower_bound) / step_size);
+  value -= (lower_bound + static_cast<float>(lower_index) * step_size);
+  if (value == 0) return colormap[lower_index];
+  auto interpolate = [](std::uint8_t lower, std::uint8_t upper, float step_size, float value) {
+    return (lower == upper) ? lower : static_cast<std::uint8_t>(static_cast<float>(lower) + ((static_cast<float>(upper) - static_cast<float>(lower)) / step_size) * value);
```
Comment (kunaltyagi) [inline test/filters/test_convolution.cpp:70]: Please check the formula.

File: test/filters/test_convolution.cpp [hunk 25]
```diff
@@ -3155,6 +3158,266 @@ main (int argc, char** argv)
...
+  output_47[57] = 101.363;
+  output_47[58] = 100.821;
+  output_47[59] = 100.538;
+  output_47[60] = 100.332;
+  output_47[61] = 0;
+  output_47[62] = 0;
+  output_47[63] = 0;
+
+  std::uint32_t j = 0;
+  for (std::uint32_t i = 0; i < output->width ; ++i)
```
Comment (kunaltyagi) [inline test/filters/test_convolution.cpp:3304]: Please reproduce the note here also

File: test/filters/test_convolution.cpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp]: Ok

File: test/filters/test_convolution.cpp (hunk 25 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:3304]: I am currently mapping the input data of the first test through an algorithm. Furthermore, I have generated comparison data for all tests, which I am building in.

File: test/filters/test_convolution.cpp (hunk 23 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:64]: Ok

File: test/filters/test_convolution.cpp (hunk 24 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:70]: The formula is correct. I've checked the function: https://gist.github.com/OgreTransporter/3962b7a6a7f5f6e6b34598b30fc88558

**Comment by kunaltyagi** [comment]
Haven't reviewed, but I love the 3000 removed lines 😄 

PS: tests failing

**Comment by OgreTransporter** [comment]
Yes, I have made a mathematical approximation to the original data and then determined the new output data. In addition, I have also determined output data for the other tests. I did not add the data line by line to an array - as in the original test - but initialized it as a fixed array. Fewer lines and you can test comfortably.

The macOS build failed due to a signed/unsigned comparison. Nothing happens with GCC, under MSVC there is a compiler warning and under OSX it is an error.

**Comment by SunBlack** [comment]
> The macOS build failed due to a signed/unsigned comparison. Nothing happens with GCC, under MSVC there is a compiler warning and under OSX it is an error.

The macOS build is configured with warnings as errors, during the other not (now) - that's why the build is failing only on macOS.

File: test/filters/test_convolution.cpp [hunk 26]
```diff
@@ -41,3120 +41,371 @@
...
   pcl::filters::Convolution<PointXYZI, PointXYZI> convolve;
-  PointCloud<PointXYZI>::Ptr output;
-  output.reset (new PointCloud<PointXYZI> ());
+  convolve.setInputCloud(input);
+  convolve.setKernel(filter);
+  convolve.convolveRows(*output);
+
+  // output rows
+  // note: this is because of border policy ignore which sets the border of width = filter_size/2 as NaN for xyz and 0 for values
+  std::array<float, 128> output_results {
```
Comment (kunaltyagi) [inline test/filters/test_convolution.cpp:109]:
```suggestion
  std::array<float, 128> output_intensity {
```

File: test/filters/test_convolution.cpp [hunk 27]
```diff
@@ -41,3120 +41,371 @@
...
+  // output rows (first and last row)
+  // note: this is because of border policy ignore which sets the border of width = filter_size/2 as NaN for xyz and 0 for rgb values
+  std::array<std::uint8_t, 384> output_results {
```
Comment (kunaltyagi) [inline test/filters/test_convolution.cpp:213]: An array of RGB would make more sense. Maybe even an array of array of RGB

File: test/filters/test_convolution.cpp [hunk 28]
```diff
@@ -41,3120 +41,371 @@
...
+  // filter
+  auto output = pcl::make_shared<PointCloud<PointXYZRGB>>();
+  pcl::filters::Convolution<PointXYZRGB, PointXYZRGB> convolve;
+  convolve.setInputCloud (input);
+  convolve.setKernel (filter);
+  convolve.convolveRows (*output);
+
+  // output rows (first and last row)
+  // note: this is because of border policy ignore which sets the border of width = filter_size/2 as NaN for xyz and 0 for rgb values
+  std::array<std::uint8_t, 384> output_results {
```
Comment (kunaltyagi) [inline test/filters/test_convolution.cpp:327]: Same comment wrt name and datatype here

**Comment by OgreTransporter** [comment]
> You've mentioned that you copied the tests. If this refactoring didn't touch those tests, could you create an issue with the details of the tests that can be refactored too? Thanks for the work you've put in for this (these) PR

Unfortunately the statement is no longer true. The test principle of generating and filtering inputs and comparing the outputs is still the same. But by approximating the data, new results have come out. So the original test has been renewed as well.

File: test/filters/test_convolution.cpp (hunk 27 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:213]: Yes, I have changed the data type. I would keep the array field like this, because this way the two rows can be mapped compactly as columns. I add an inline comment to the description.

File: test/filters/test_convolution.cpp (hunk 28 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:327]: Same solution

File: test/filters/test_convolution.cpp (hunk 26 above)
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:109]: Yes

File: test/filters/test_convolution.cpp [hunk 29]
```diff
@@ -41,3120 +41,371 @@
...
-TEST (Convolution, convolveRows)
+RGB interpolate_color(float lower_bound, float upper_bound, float value)
 {
-  using namespace pcl::common;
-  using namespace pcl::filters;
+  if (value <= lower_bound) return colormap[0];
+  if (value >= upper_bound) return colormap.back();
+  float step_size = (upper_bound - lower_bound) / static_cast<float>(colormap.size() - 1);
+  std::size_t lower_index = static_cast<std::size_t>((value - lower_bound) / step_size);
+  value -= (lower_bound + static_cast<float>(lower_index) * step_size);
```
[the remark this answers is not in the document]
Comment (OgreTransporter) [reply test/filters/test_convolution.cpp:67]: I skipped the normalization and used only normal [linear interpolation](https://en.wikipedia.org/wiki/Linear_interpolation#Linear_interpolation_as_approximation) because I didn't want to make it more complicated. Everybody has probably learned linear interpolation at school, normalizing values is less common.

**Comment by OgreTransporter** [comment]
```
d:\a\1\s\surface\include\pcl\surface\impl\surfel_smoothing.hpp(84): fatal error C1083: Cannot open compiler intermediate file: 'pcl_surface.dir\Release\mls.obj': Not enough space [D:\a\build\surface\pcl_surface.vcxproj]
LINK : fatal error LNK1257: code generation failed [D:\a\build\surface\pcl_surface.vcxproj]
```
This time it's not my fault ;-)

**Comment by kunaltyagi** [comment]
@SunBlack, @larshg Could you please give this a look over? Especially the tests. If everything is ok, let's merge this to master

**Comment by larshg** [comment]
I have build without PR: pcl_train_linemod_template failed with linking errors as expected.
Build with PR: pcl_train_linemod_template is build succesfully.
The modified and new unit tests runs successfully.

I haven't verified the approximation of the original data, nor reasoned anything about its correctness in general.

But it compiles and run. I have only launched the pcl_train_linemod_template, without any arguments. But I just assume it works as it hasn't changed per se.

**Comment by kunaltyagi** [comment]
Thanks @larshg

Let's merge this
