### PR TITLE
Fixed if/ifdef WIN32 issues

### LINKED ISSUE #3667: Error with "#if WIN32" in pcd_grabber.cpp?
I think this is not valid code if WIN32 is not defined: 
```
#if WIN32
```
https://github.com/PointCloudLibrary/pcl/blob/master/io/src/pcd_grabber.cpp#L207

Should it be changed to an `ifdef` instead?

For context: I'm trying to compile PCL on Windows using MSYS2, and I got the following error:
```
C:/msys64/home/filip.sund/code/pcl/io/src/pcd_grabber.cpp:207:10: error: #if with no expression
  207 | #if WIN32
      |          ^
```

Since I'm using MSYS2 it means I'm only kind-of on WIN32. I think? I'm not sure of the exact details here, unfortunately. I've tried changing it to an `ifdef`, and it seems to compile fine.

### PR DESCRIPTION
**Pull request by FSund**
Fixes #3667

Replaced all occurrences (a scary sentence) of `#if WIN32`, `#if _WIN32` and other variants with the proper `#ifdef` or `#ifndef`, in all `*.cpp`, `*.h` and `*.hpp` files, as discussed in #3667.

I'm not sure if I was supposed to touch `_WIN32` occurrences, but have done so anway.

Please do check my work.

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Apparently, WIN32 is an error. There is [no such macro](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019). Only _WIN32 exists. [This is a handy guide](https://blog.kowalczyk.info/article/j/guide-to-predefined-macros-in-c-compilers-gcc-clang-msvc-etc..html). I have no idea if other such errors are lurking around 😱

File: io/src/pcd_grabber.cpp [hunk 1]
```diff
@@ -204,7 +204,7 @@ bool
 pcl::PCDGrabberBase::PCDGrabberImpl::readTARHeader ()
 {
   // Read in the header
-#if WIN32
+#ifdef WIN32
```
Comment (kunaltyagi) [inline io/src/pcd_grabber.cpp]: The author probably meant `_WIN32`

```suggestion
#ifdef _WIN32
```

**Comment by FSund** [comment]
I'm pretty sure I saw some `#define WIN32` somewhere along the way when replacing the others, so there might be some instances of `WIN32` internally. I'll have a look tomorrow.

**Comment by FSund** [comment]
I went ahead and checked for any `#if WIN64` and `#if _WIN64` issues, but couldn't find any, so that's good.

Any idea why the tests are failing? I'm not that familiar with how to read those Azure logs.

**Comment by kunaltyagi** [comment]
#3656 is the cause. Don't worry

**Comment by taketwo** [comment]
Offtopic: @kunaltyagi  I think it makes sense if this PR is included in the changelog. If we make changelog inclusion "opt-in", then this needs to be labeled somehow. But this is neither of "changelog: x" that we have at the moment. Do we need something like "changelog: fix"?

**Comment by kunaltyagi** [comment]
I'd say that instead of manually creating the changelog, have sufficient labels to enable automatic generation. It doesn't take long to label each PR. Would speed up releases. Would be a giant help in automatic releases (eg: Azure has a release pipeline which can be created and triggered whenever you'd want a new release) since there's no (maybe reduced) manual work
