### PR TITLE
Fix rendering of points.

### LINKED ISSUE #4040: [tools] pcl_viewer does not show clouds anymore
In commit fa71f8044598cd7c285be7bbca22acb6cd39e807, the `pcl_viewer` binary does not display clouds anymore. I have tested with the `test/colored_cloud.pcd` PCD file. It still works in tag `pcl-1.9.1`.

**Expected behavior**
Cloud from pcd file is shown

**Current Behavior**

Black viewport, no cloud.

**To Reproduce**

1. Compile aforementioned commit from source
2. Run `./bin/pcl_viewer ../test/colored_cloud.pcd`

**Your Environment (please complete the following information):**

 - OS: ElementaryOS Hera (Ubuntu 18.04)
 - Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.
 - PCL Version fa71f8044598cd7c285be7bbca22acb6cd39e807

### PR DESCRIPTION
**Pull request by larshg**
Fixes #4040.

The culprit was the "memory leak" fixed in #3687.

Note:

Can we in some way avoid the memcpy - or maybe concatenate them to a single copy? 
The XYZ will always be aligned?

Are we preparing to change at compile time, the underlaying datatype, ie. switch between float and double. Then this would require a bit more revamp I guess :)

### CODE REVIEW

**Comment by kunaltyagi** [comment]
> The XYZ will always be aligned?

This is not a guarantee (and stated explicitly in PCL's codebase)

> to change at compile time, the underlaying datatype

In future maybe. I don't have any plans for that right now.

> The culprit was the "memory leak" fixed in #3687

The leak was needed, as in `SetArray` takes ownership of the array?

**Comment by kunaltyagi** [comment]
Adding to milestone since it is a fix to regression in a key feature

**Comment by larshg** [comment]
> > The XYZ will always be aligned?
> 
> This is not a guarantee (and stated explicitly in PCL's codebase)
>

So best to keep the single copy for each component I guess.
 
> > to change at compile time, the underlaying datatype
> 
> In future maybe. I don't have any plans for that right now.
> 

Oki, I won't overthink this then and keep it as is.

> > The culprit was the "memory leak" fixed in #3687
> 
> The leak was needed, as in `SetArray` takes ownership of the array?

Yes, the 0 (save) indicates that the array should be deleted by VTK. Also, since no delete method is explicit set (overload of `SetArray`), its default is `free()`.

I'm unsure exactly how VTK expands its array, with the AddNextTuple vs. us allocating the full array, so a benchmark would have been nice :)

But yes, I also think its simpler to read now. 

There are places in the color handles that has the same procedure, which could be simplified, though again I'm not sure if it gives a small performance/memory degradation.

**Comment by larshg** [comment]
I think if it adds a point, which there is no space for, it increase its array with 1 / numberofcomponents, which is 3 (XYZ), each time it expands its array.
So this gives a overshoot.

Maybe, go back to the array/malloc approach.

**Comment by larshg** [comment]
Fixed it, with adding call to `resize `before adding values to the array.

File: visualization/src/point_cloud_handlers.cpp [hunk 1]
```diff
@@ -686,56 +686,53 @@ pcl::visualization::PointCloudGeometryHandler<pcl::PCLPointCloud2>::getGeometry
 
   vtkSmartPointer<vtkFloatArray> data = vtkSmartPointer<vtkFloatArray>::New ();
   data->SetNumberOfComponents (3);
+  
   vtkIdType nr_points = cloud_->width * cloud_->height;
+  
+  if (!data->Resize(nr_points))
+    PCL_ERROR("Failed to allocate space for points in VTK array");
```
Comment (SergioRAgostinho) [inline visualization/src/point_cloud_handlers.cpp:693]: Should we throw here?

File: visualization/src/point_cloud_handlers.cpp [hunk 2]
```diff
@@ -686,56 +686,53 @@ pcl::visualization::PointCloudGeometryHandler<pcl::PCLPointCloud2>::getGeometry
...
   // If the dataset has no invalid values, just copy all of them
   if (cloud_->is_dense)
   {
     for (vtkIdType i = 0; i < nr_points; ++i, point_offset+=cloud_->point_step)
-    {
+    {      
       // Copy the value at the specified field
-      memcpy (&dim, &cloud_->data[point_offset + cloud_->fields[field_x_idx_].offset], sizeof (float));
-      pts[i * 3 + 0] = dim;
+      memcpy (&x, &cloud_->data[point_offset + cloud_->fields[field_x_idx_].offset], sizeof (float));
```
Comment (SergioRAgostinho) [inline visualization/src/point_cloud_handlers.cpp:705]: Any chance we can reduce this to a simple float assignment instead of calling memcpy?

File: visualization/src/point_cloud_handlers.cpp (hunk 1 above)
Comment (larshg) [reply visualization/src/point_cloud_handlers.cpp:693]: What to throw? Do we have a PCLOutOfMemoryException or something similar?

File: visualization/src/point_cloud_handlers.cpp (hunk 2 above)
Comment (larshg) [reply visualization/src/point_cloud_handlers.cpp:705]: I did think about it, but I'm unsure how to correctly cast the _data (uint_8) arraypointer

Comment (larshg) [reply visualization/src/point_cloud_handlers.cpp:705]: Something like this - not sure if thats prettier.
```
const float* xPointer = (const float*)&cloud_->data[point_offset + cloud_->fields[field_x_idx_].offset];
data->InsertNextValue(xPointer[0]);
```

Comment (kunaltyagi) [reply visualization/src/point_cloud_handlers.cpp:705]: Yes, but use `static_cast`

File: common/include/pcl/exceptions.h [hunk 3]
```diff
@@ -262,4 +262,17 @@ namespace pcl
                           unsigned line_number = 0)
       : pcl::PCLException (error_description, file_name, function_name, line_number) { }
   };
+
+  /** \class OutofMemoryException
+    * \brief An exception that is thrown when out of memory.
+    */
+  class OutOfMemoryException : public PCLException
```
Comment (kunaltyagi) [inline common/include/pcl/exceptions.h:269]: [c++ has one](https://en.cppreference.com/w/cpp/memory/new/bad_alloc), which I'd try to catch. It'd be better if you inherit from both (somehow, it might cause a diamond inheritance, just something to watch out for)

File: visualization/src/point_cloud_handlers.cpp (hunk 2 above)
Comment (larshg) [reply visualization/src/point_cloud_handlers.cpp:705]: I'm getting invalid type conversion, when using static_cast?

Comment (larshg) [reply visualization/src/point_cloud_handlers.cpp:705]: reinterpret_cast seems to work?

Comment (SergioRAgostinho) [reply visualization/src/point_cloud_handlers.cpp:705]: Try static first (likely won't work) and move to reinterpret if the first one fails
```cpp
const float* ptr = static_cast<const float*>(&cloud_->data[point_offset + cloud_->fields[field_x_idx_].offset]);
data->InsertNextValue(*ptr);
```

File: visualization/src/point_cloud_handlers.cpp (hunk 1 above)
Comment (SergioRAgostinho) [reply visualization/src/point_cloud_handlers.cpp]: Your solution looks good.

File: common/include/pcl/exceptions.h (hunk 3 above)
Comment (SergioRAgostinho) [reply common/include/pcl/exceptions.h]: Kunal brings a good point into the table. PCLException derives from std::runtime_error and we're clearly handling a bad_aloc situation. The quickest fix for me at the moment would be to throw a simple bad_aloc, cheap and dirty. We can address the limitations of PCLException in another issue and this one would be fixed.

Comment (larshg) [reply common/include/pcl/exceptions.h]: Should be changed now. I have added a PCL_ERROR just before, to give a bit of help figure out where the exception throws.

File: visualization/src/point_cloud_handlers.cpp [hunk 4]
```diff
@@ -686,56 +686,55 @@ pcl::visualization::PointCloudGeometryHandler<pcl::PCLPointCloud2>::getGeometry
...
+  }
+    
 
   // Add all points
-  float dim;
-  vtkIdType j = 0;    // true point index
-  std::vector<float> pts (nr_points * 3);
   int point_offset = 0;
 
+  const float* ptr = nullptr;
```
Comment (kunaltyagi) [inline visualization/src/point_cloud_handlers.cpp:702]: Move this into the for loops please

Comment (larshg) [reply visualization/src/point_cloud_handlers.cpp:702]: Then I have to add two? Each in one for loop.

Comment (kunaltyagi) [reply visualization/src/point_cloud_handlers.cpp:702]: The first invocation can have an extra `const float*`. No need to declare it separately.

**Comment by themightyoarfish** [comment]
Confirmed to fix #4040 on osx.
