### PR TITLE
Fixed bug incorrectly copying adjacent points in fromPCLPointCloud2()

### LINKED ISSUE #1802: Bug in fromPCLPointCloud2()
fromPCLPointCloud2() contains this test

    // Check if we can copy adjacent points in a single memcpy
    if (field_map.size() == 1 &&
        field_map[0].serialized_offset == 0 &&
        field_map[0].struct_offset == 0 &&
        msg.point_step == sizeof(PointT))
    {
        ... copy an entire row/cloud with a single memcpy() ...
    }

Unfortunately this test is not strict enough, as it does not test that field_map[0].size == sizeof(PointT).
Here is a test case:

    PointCloud<PointXYZ> test;
    loadPLYFile("test.ply", test);

test.ply:

    ply
    format ascii 1.0
    element vertex 3
    property float x
    property float y
    property float z
    property uchar red
    property uchar green
    property uchar blue
    property uchar alpha
    element face 0
    property list uchar int vertex_indices
    end_header
    1.0 2.0 3.0 255 255 255 255 
    4.0 5.0 6.0 255 255 255 255 
    7.0 8.0 9.0 255 255 255 255 

Note that in this example, msg.point_step is 16 and sizeof(PointXYZ) is also 16.
createMapping() correctly determines that we should copy the 3 float fields x,y,z (12 bytes) for each point and discard the RGBA, and creates a field_map with one entry having size 12.  Clearly the fields are not contiguous and we must copy one point at a time.  However the above test will pass (since 16 == 16), and the data[3] of each PointXYZ is overwritten with RGBA data, becoming NaN (0xFFFFFFFF).

## Possible Solution
I changed the test above to:

    // Check if we can copy adjacent points in a single memcpy
    if (field_map.size() == 1 &&
        field_map[0].serialized_offset == 0 &&
        field_map[0].struct_offset == 0 &&
        field_map[0].size == msg.point_step &&
        field_map[0].size == sizeof(PointT))
    {

That is, field_map[0].size must be the entire size of both the input and output types.
This fixes my specific case, can't say it is correct for all.

## Code to Reproduce
See above

### PR DESCRIPTION
**Pull request by Chungzuwalla**
fixes #1802.
fromPCLPointCloud2() tried to copy clouds an entire row at a time, provided the source and destination point types were the same size, even if only part of each point was to be copied.  This would incorrectly overwrite all fields of the destination points with irrelevant source data.

### CODE REVIEW

File: common/include/pcl/conversions.h [hunk 1]
```diff
@@ -180,11 +180,14 @@ namespace pcl
...
-    // Check if we can copy adjacent points in a single memcpy
+    // Check if we can copy adjacent points in a single memcpy.  We can do so if there
+    // is exactly one field to copy and it is the same size as the source and destination
+    // point types.
     if (field_map.size() == 1 &&
         field_map[0].serialized_offset == 0 &&
         field_map[0].struct_offset == 0 &&
-        msg.point_step == sizeof(PointT))
+        field_map[0].size == msg.point_step &&
+        field_map[0].size == sizeof(PointT))
```
Comment (jspricke) [inline common/include/pcl/conversions.h]: I think it would read easier if we would leave the `msg.point_step == sizeof(PointT))`. But after all it's the same, right?

Comment (Chungzuwalla) [inline common/include/pcl/conversions.h]: I think the comment makes clear that the source msg, destination type and field must all be the same size.  Happy to get a consensus from others though.

BTW the Travis checks seem to have failed because compiling the unit tests exceeded the allowed time.  Is that normal?

Comment (taketwo) [inline common/include/pcl/conversions.h]: I don't see any difference.
Regarding tests: yes, that's normal :(

**Comment by taketwo** [comment]
Any objections to merging this?
