### PR TITLE
Fix division and subtraction operators

### LINKED ISSUE #2465: Unexpected results for the operators / and - between a scalar and a pcl point type
## Your Environment

* PCL Version: master

## Context

```.cpp
    pcl::PointXY p;
    p.x = 10;
    p.y = 20;
    using namespace pcl::common;
    std::cout << "p/2: " << p/2 << "\n";
    std::cout << "2/p: " << 2/p << "\n";
    std::cout << "p-2: " << p-2 << "\n";
    std::cout << "2-p: " << 2-p << "\n";
```
output:
```
p/2: (5,10)
2/p: (5,10)
p-2: (8,18)
2-p: (8,18)
```

That is `p/2` and `2/p` give the same result. The same problem applies to `p-2` and `2-p`.

## Expected Behavior

`2/p` should be `(2/p.x, 2/p.y)`
and
`2-p` should be `(2-p.x, 2-p.y)`

## Possible Solution

Change the following two functions
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/register_point_struct.h#L285-L286

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/register_point_struct.h#L305-L306

### PR DESCRIPTION
**Pull request by mvieth**
Please see commit messages.
Closes #2510
Fixes #2465 (this is already closed, but apparently not actually fixed)

### CODE REVIEW

File: common/include/pcl/register_point_struct.h [hunk 1]
```diff
@@ -189,6 +189,23 @@ namespace pcl
       for (std::uint32_t i = 0; i < count; ++i)
         p[i] /= scalar;
     }
+
+    template<typename T1, typename T2> inline
```
Comment (kunaltyagi) [inline common/include/pcl/register_point_struct.h:193]: Thoughts on calling it ArrayT and ScalarT?

**Review by kunaltyagi — APPROVED** [review]

File: common/include/pcl/register_point_struct.h (hunk 1 above)
Comment (mvieth) [reply common/include/pcl/register_point_struct.h:193]: Renaming T2 to ScalarT would fit, but T1 is not an array type in both versions of `divscalar2` (in this version `std::is_array<T1>` returned false). I could rename T1 to `NoArrayT` here and to `ArrayT` below, if you think that makes it clearer?

Comment (kunaltyagi) [reply common/include/pcl/register_point_struct.h:193]: Yes please

**Review by kunaltyagi — APPROVED** [review]

**Review by larshg — APPROVED** [review]
