### PR TITLE
VTK function change since version 7.1

### LINKED ISSUE #2060: error: ‘class vtkUnsignedCharArray’ has no member named ‘InsertNextTupleValue’ colors->InsertNextTupleValue (color);
* PCL Version: 1.8
* VTK 9.0
* Ubuntu 16.04

The error is caused because VTK version < 7 has `InsertNextTupleValue` but  the name is changed in newer versions of VTK.

Solution: Change the source code like the following:
```
491         // two times since we add also two points per edge
492 #if VTK_MAJOR_VERSION < 7
493         colors->InsertNextTupleValue (color);
494         colors->InsertNextTupleValue (color);
495 #else
496         colors->InsertNextTypedTuple(color);
497         colors->InsertNextTypedTuple(color);
498 #endif
```
This is according to `https://www.vtk.org/doc/nightly/html/VTK-7-1-Changes.html` which says:
The old and new method names are listed below:
    `GetTupleValue` is now `GetTypedTuple`
    `SetTupleValue` is now `SetTypedTuple`
    `InsertTupleValue` is now `InsertTypedTuple`
    `InsertNextTupleValue` is now `InsertNextTypedTuple`

### PR DESCRIPTION
**Pull request by yongduek**
before VTK 7.1
  `InsertNextTupleValue` 
after
  `InsertNextTypedTuple`

This change is required if you use VTK version >= 7.1.

**Maintainer edit:** fixes #2060.

### CODE REVIEW

File: examples/segmentation/example_cpc_segmentation.cpp [hunk 1]
```diff
@@ -489,9 +489,13 @@ CPCSegmentation Parameters: \n\
           color = concave_color;
 
         // two times since we add also two points per edge
+#if (VTK_MAJOR_VERSION < 7) || (VTK_MAJOR_VERSION==7 && VTK_MINOR_VERSION==0)
```
Comment (taketwo) [inline examples/segmentation/example_cpc_segmentation.cpp]: Please add spaces around `==`

File: examples/segmentation/example_cpc_segmentation.cpp [hunk 2]
```diff
@@ -489,9 +489,13 @@ CPCSegmentation Parameters: \n\
...
         colors->InsertNextTupleValue (color);
         colors->InsertNextTupleValue (color);
-
+#else       
+        colors->InsertNextTypedTuple(color);
```
Comment (taketwo) [inline examples/segmentation/example_cpc_segmentation.cpp]: Please add spaces between function name and brackets

**Comment by taketwo** [comment]
Thanks for contributing!
