### PR TITLE
Check and warn user about missing normals in `OrganizedMultiPlaneSegmentation`

### LINKED ISSUE #3855: [segmentation] Improve error handling in OrganizedMultiPlaneSegmentation::segment
When using OrganizedMultiPlaneSegmentation, if the user does not specify _both_ an input cloud _and_ normals they will experience a segfault. This is because those pointers are dereferenced on line 95, without first checking if the pointers are valid:
* https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/impl/organized_multi_plane_segmentation.hpp#L95-L101

I suggest adding additional guard clauses before line 95 to check for valid inputs. 

```c++
  if ( !input_ )
  {
    PCL_ERROR ("[pcl::%s::segment] You must provide a valid input cloud.\n",
               getClassName ().c_str ());
    return;
  }

  if ( !normals_ )
  {
    PCL_ERROR ("[pcl::%s::segment] You must provide a valid input normals.\n",
               getClassName ().c_str ());
    return;
  }
```

Alternatively it could throw an exception... but I figured it's better to match the other error handling inside this file.

I'm happy to open a PR if one or the other approach sounds good

### PR DESCRIPTION
**Pull request by daniel-packard**
fixes #3855 

Add guard clauses and error messages as described in the related issue.

### CODE REVIEW

File: segmentation/include/pcl/segmentation/impl/organized_multi_plane_segmentation.hpp [hunk 1]
```diff
@@ -91,6 +91,20 @@ pcl::OrganizedMultiPlaneSegmentation<PointT, PointNT, PointLT>::segment (std::ve
   if (!initCompute ())
     return;
 
+  // Check that the input cloud is present
+  if (!input_)
```
Comment (kunaltyagi) [inline segmentation/include/pcl/segmentation/impl/organized_multi_plane_segmentation.hpp:95]: `input_` check is done in `PCLBase` where this same condition exits silently via L92. So, your L94-100 are never executed

You can also choose to exit silently on L91 using `if (!initCompute() || !normals_) { return; }`

Comment (daniel-packard) [reply segmentation/include/pcl/segmentation/impl/organized_multi_plane_segmentation.hpp:95]: Do we want to exit silently? This seems unhelpful to the user (me)

Comment (kunaltyagi) [reply segmentation/include/pcl/segmentation/impl/organized_multi_plane_segmentation.hpp:95]: > Do we want to exit silently?

No idea 😆 Just reporting what's already in the code.

Comment (daniel-packard) [reply segmentation/include/pcl/segmentation/impl/organized_multi_plane_segmentation.hpp:95]: How about I remove the check on `input_` , but keep the check here on `normals_` with the error reporting? It's more in line with the other error checking in this file that way, which I feel is helpful.

Maybe we can open a separate issue to discuss if PCLBase::initCompute should report additional error messages instead of exiting silently?

Comment (daniel-packard) [reply segmentation/include/pcl/segmentation/impl/organized_multi_plane_segmentation.hpp]: dev
