### PR TITLE
fix in toPCLPointCloud2 if input cloud has no points

### LINKED ISSUE #1716: toPCLPointCloud2 crashes if cloud has no points
Dear PCL Team,

the method toPCLPointCloud2 (conversion.h) crashes in line 257 if the incoming cloud contains no points:

`memcpy (&msg.data[0], &cloud.points[0], data_size);`

since data_size is 0.

My environment: Visual Studio 2013, 64bit, PCL 1.8.0 (current master branch), Win 7.

Would it be possible, to replace the line by:

`
if (data_size)
{
    memcpy (&msg.data[0], &cloud.points[0], data_size);
}
`

Cheers
Marc

### PR DESCRIPTION
**Pull request by magro11**
Fixes #1716

### CODE REVIEW

File: common/include/pcl/conversions.h [hunk 1]
```diff
@@ -254,7 +254,10 @@ namespace pcl
     // Fill point cloud binary data (padding and all)
     size_t data_size = sizeof (PointT) * cloud.points.size ();
     msg.data.resize (data_size);
-    memcpy (&msg.data[0], &cloud.points[0], data_size);
+    if (data_size)
```
Comment (stefanbuettner) [inline common/include/pcl/conversions.h]: I'd write data_size > 0 to be clear what's happening although it's equivalent since it's of type size_t.
