### PR TITLE
Fixes #1433

### LINKED ISSUE #1433: loadPLYFile() does not support NaN values
Test code
---
```cpp
#include <pcl/common/common.h>
#include <pcl/console/parse.h>
#include <pcl/point_cloud.h>
#include <pcl/io/ply_io.h>
#include <pcl/visualization/pcl_visualizer.h>

int main(int argc, char* argv[])
{
  std::vector<int> ply_args = pcl::console::parse_file_extension_argument (argc, argv, ".ply");
  if (ply_args.size() != 1)
  {
    PCL_ERROR("Usage: %s input.ply\n", argv[0]);
    return -1;
  }

  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZ>);
  if (pcl::io::loadPLYFile(argv[ply_args[0]], *cloud) != 0)
  {
    PCL_ERROR("Could not load %s\n", argv[ply_args[0]]);
    return -1;
  }

  pcl::visualization::PCLVisualizer viewer;
  viewer.addPointCloud(cloud);
  viewer.spin();
  return 0;
}
```

File 1
```
format ascii 1.0
comment VCGLIB generated
element vertex 4
property float x
property float y
property float z
element face 0
property list uchar int vertex_indices
end_header
4.23607 0 1.61803 
2.61803 2.61803 2.61803 
0 1.61803 4.23607 
0 -1.61803 4.23607 
```

File 2
```
format ascii 1.0
comment VCGLIB generated
element vertex 4
property float x
property float y
property float z
element face 0
property list uchar int vertex_indices
end_header
4.23607 nan 1.61803 
2.61803 2.61803 2.61803 
0 1.61803 4.23607 
0 -1.61803 4.23607 
```

File 3
```
format ascii 1.0
comment VCGLIB generated
element vertex 4
property float x
property float y
property float z
element face 0
property list uchar int vertex_indices
end_header
4.23607 NaN 1.61803 
2.61803 2.61803 2.61803 
0 1.61803 4.23607 
0 -1.61803 4.23607 
```

Output error:
---
Happens with `file_2` and `file_3`
```
$ ./test_pcl_1 ~/file_2.ply 
[pcl::PLYReader] /home/victor/file_2.ply:9: property 'list uint8 int32 vertex_indices' of element 'face' is not handled
[pcl::PLYReader] /home/victor/file_2.ply:11: parse error
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!
Could not load /home/victor/file_2.ply

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
If the conversion fails, it will default to a quiet nan of the type in question. This mimics what I think it was the original intended behavior.

### CODE REVIEW

File: io/include/pcl/io/ply/ply_parser.h [hunk 1]
```diff
@@ -559,9 +559,16 @@ inline bool pcl::io::ply::ply_parser::parse_scalar_property (format_type format,
...
+    std::string value_s;
     scalar_type value = std::numeric_limits<scalar_type>::quiet_NaN ();
     char space = ' ';
-    istream >> value;
+    istream >> value_s;
+    try
+    {
+      value = boost::lexical_cast<scalar_type> (value_s);
+    }
+    catch (boost::bad_lexical_cast &) {}
```
Comment (jspricke) [inline io/include/pcl/io/ply/ply_parser.h]: we should put in some default in case it fails, or don't catch the exception.

Comment (SergioRAgostinho) [inline io/include/pcl/io/ply/ply_parser.h]: I have the impression that ```boost::lexical_cast```only throws ```boost::bad_lexical_cast``` exceptions, but I can extend it for std::exception. 

If the conversion fails ```value``` maintains its original value, in this case ```std::numeric_limits<scalar_type>::quiet_NaN```. [Here's](http://en.cppreference.com/w/cpp/types/numeric_limits/quiet_NaN) the actual value based on each type, for reference.

Comment (jspricke) [inline io/include/pcl/io/ply/ply_parser.h]: sorry, should have been clearer, the code should read:
```
scalar_type value;
try
    {
      value = boost::lexical_cast<scalar_type> (value_s);
    }
    catch (boost::bad_lexical_cast &)
   {
       value = std::numeric_limits<scalar_type>::quiet_NaN ();
   }
```

**Comment by SergioRAgostinho** [comment]
Found a similar pattern of nan parsing in ```pcl::io::ply::ply_parser::parse_list_property```. Applied the same logic.

**Comment by VictorLamoine** [comment]
:+1:

**Comment by taketwo** [comment]
Hi Sergio, thanks for helping us to make PCL better! A small suggestion from my side though: when you create a pull request, could you put a brief summary in the title, and move the "Fixes xxx" statement to the description? The thing is, GitHub does not parse the title, so it does not establish a link between the pull request and the corresponding issue. Observe that for example in this pull request the title has no hyperlink, so there is no quick way to jump directly to the original issue. (Only by manually modifying the URL.) And vice versa, if you now go to the 1433 issue, you will find no way to know which pull request fixed it. (Only the commit that fixed it is visible.) If you follow my suggestion, then everything will be hyperlinked and easily navigable. Thanks!

**Comment by SergioRAgostinho** [comment]
Wilco :+1:
