### PR TITLE
Warn user of unorganized PCD for pcl_train_linemod_template

### LINKED ISSUE #3633: Segmentation fault when running pcl_train_linemod_template
## Your Environment

* Operating System and version: Linux Ubuntu 18.04
* Compiler: g++
* PCL Version: source pcl/master and deb 1.8

## Context
I'm trying to use the commandline tools included with pcl to generate LineMOD templates for objects in the YCB dataset. I ran the following:
```
pcl_train_linemod_template /path/to/ycb/pcd/file.pcd
```
The pcd file was generated using `pcl_ply2pcd -format 1 /ply/input.ply /pcd/output.pcd`.

## Current Behavior

I received a seg fault error in the `compute()` method. Downloaded the source file to run gdb and got this traceback:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555592b16 in pcl::filters::Convolution<pcl::RGB, pcl::RGB>::makeInfinite (this=0x7fffffffce90, p=...) at /home/pcl/filters/include/pcl/filters/impl/convolution.hpp:398
398           p.r = 0; p.g = 0; p.b = 0;
``` 

Further debugging shows that the above occurs on line 160 of `train_linemode_template.cpp`:
```
color_grad_mod.processInputData ();
```

## Code to Reproduce

1. Download the data fom [here](http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/data/berkeley/002_master_chef_can/002_master_chef_can_berkeley_rgbd.tgz)
2. Convert the `.ply` file in `clouds/` to `.pcd` using `pcl_ply2pcd -format 1`
3. Train LineMOD template `pcl_train_linemod template /path/to/pcd/file`

### PR DESCRIPTION
**Pull request by truhoang-ubtrobot**
Added a check to warn user whether input PCD files are unorganized. If check fails, skip to next input file. Added counter to output error if all input files fail.

Fixes #3633

### CODE REVIEW

File: tools/train_linemod_template.cpp [hunk 1]
```diff
@@ -284,5 +294,10 @@ main (int argc, char** argv)
     compute (cloud, min_depth, max_depth, max_height, pcd_filename, sqmmt_filename);
   }
 
+  if (unorganized_pcd_cnt == p_file_indices.size())
+  {
+    print_error("All input pcd files are unorganied.\n");
```
Comment (kunaltyagi) [inline tools/train_linemod_template.cpp]:
```suggestion
    print_error("All input pcd files are unorganized.\n");
```

File: tools/train_linemod_template.cpp [hunk 2]
```diff
@@ -261,15 +261,25 @@ main (int argc, char** argv)
...
     // Load input file
     const std::string input_filename = argv[p_file_index];
     PointCloudXYZRGBA::Ptr cloud (new PointCloudXYZRGBA);
+  
     if (!loadCloud (input_filename, *cloud)) 
       return (-1);
 
+    if (!cloud->isOrganized())
+    {
+      std::string warn_msg = "Loaded point cloud is not organized. Skipping " + input_filename + ".\n";
```
Comment (kunaltyagi) [inline tools/train_linemod_template.cpp]:
```suggestion
      std::string warn_msg = "Unorganized point cloud detected. Skipping file " + input_filename + "\n";
```

File: tools/train_linemod_template.cpp [hunk 3]
```diff
@@ -261,15 +261,25 @@ main (int argc, char** argv)
   float max_height = std::numeric_limits<float>::max ();
   parse_argument (argc, argv, "-max_height", max_height);
 
+  uint32_t unorganized_pcd_cnt = 0;
```
Comment (kunaltyagi) [inline tools/train_linemod_template.cpp]:
```suggestion
  std::size_t unorganized+pcd+cnt = 0;
```

Might be better to instead use a bool to detect a single organized file since that's the end aim

Comment (truhoang-ubtrobot) [reply tools/train_linemod_template.cpp]: I changed the counter type but decided to keep the counter since I think it would be nice to explicitly know if all of the input pcd files are unorganized for the use case `pcl_train_linemod_template file1.pcd file2.pcd ... fileN.pcd`

Comment (kunaltyagi) [reply tools/train_linemod_template.cpp]: Isn't that the same? `all_of(x)` == `not(any_of(not_x))` as per boolean logic

Comment (truhoang-ubtrobot) [reply tools/train_linemod_template.cpp]: I see your point. I got confused. Replaced counter with boolean logic

**Comment by kunaltyagi** [comment]
Please squash as needed.

**Comment by taketwo** [comment]
In this case, we can squash everything into a single commit during the merge.
