### PR TITLE
Fix copy constructor warning when initializing CloudView

### LINKED ISSUE #3373: GTest deprecated `TYPED_TEST_CASE`
Warning is as follows:
```
pcl/test/common/test_geometry.cpp:49:1: warning: 'TypedTestCaseIsDeprecated' is deprecated: TYPED_TEST_CASE is deprecated, please use TYPED_TEST_SUITE [-Wdeprecated-declarations]
TYPED_TEST_CASE(XYZPointTypesTest, XYZPointTypes);
^
```
This occurs in many places throughout tests.

## Your Environment
* Operating System and version: Linux
* Compiler: clang 8.0.1
* PCL Version: master

The GTest used is from the [master branch](https://github.com/google/googletest) as per the "gtest" best-practices instead of OS installed version.

## Expected Behavior
No warnings

## Possible Solution
A simple `sed` might solve this

### LINKED ISSUE #3405: Warning regarding copy ctor in cloud_view.cpp
## Your Environment
* Operating System and version: CI Ubuntu 18.04
* Compiler: gcc 5.4
* PCL Version: HEAD

## Context
Prevents #3379 from being merged

## Current Behavior

Warning as reported by the CI
```
[ 67%] Building CXX object test/features/CMakeFiles/test_cvfh_estimation.dir/test_cvfh_estimation.cpp.o
/__w/1/s/apps/cloud_composer/src/cloud_view.cpp: In copy constructor 'pcl::cloud_composer::CloudView::CloudView(const pcl::cloud_composer::CloudView&)':
/__w/1/s/apps/cloud_composer/src/cloud_view.cpp:44:1: warning: base class 'class QWidget' should be explicitly initialized in the copy constructor [-Wextra]
 pcl::cloud_composer::CloudView::CloudView (const CloudView& to_copy)
 ^
```

### PR DESCRIPTION
**Pull request by jammm**
Fixes #3405

### CODE REVIEW

File: apps/cloud_composer/src/cloud_view.cpp [hunk 1]
```diff
@@ -42,7 +42,8 @@ pcl::cloud_composer::CloudView::CloudView (ProjectModel* model, QWidget* parent)
 }
 
 pcl::cloud_composer::CloudView::CloudView (const CloudView& to_copy)
-  : vis_ (to_copy.vis_)
+  : QWidget()
```
Comment (kunaltyagi) [inline apps/cloud_composer/src/cloud_view.cpp]: Maybe including `to_copy` in [base class copy ctor](https://stackoverflow.com/a/17311455) might be useful

Comment (jammm) [reply apps/cloud_composer/src/cloud_view.cpp]: The base class (QWidget) copy constructor is private. This is the only way AFAIK.

Comment (kunaltyagi) [reply apps/cloud_composer/src/cloud_view.cpp]: You are indeed correct. [Docs](https://doc.qt.io/qt-5/qobject.html#no-copy-constructor-or-assignment-operator) tell us to use a pointer instead of subclassing 🤷‍♂ 

That's for a separate issue though
